### ISSUE TITLE
Do we force a JRE ungrade to use NG?

### ISSUE THREAD

**Issue by Ealb** [elmokki/nationgen#1034]
So right now we're not compatible with Java 1.8 because we're not. Most of our users seem to be running 1.8 JREs, if the initial failure to be able to run anything in RC8 is anything to judge by.

So the question becomes: do we force users to upgrade their JRE at this point? Java 1.8 is old, so remaining compatible is potentially a problem for us, though ATM there appears to be precisely one non-compatible method (checkRestrictions).

**Comment by elmokki** [comment]
It needs to be on top of changelog and possibly in all caps. I assume there were good reasons to go for new JRE too, but I don't know what they are.

I'd really like to rewrite the whole program in C#, but there's no way I can be arsed to do it.

**Comment by Ealb** [comment]
The plus side is Java 9+ simplified making  and reduced the footprint of JRE-free jars. The minus side is that there's no clean way to do it through an IDE, so it'll mean muddling about at the command line

**Comment by Ealb** [comment]
This should be resolved by the release scripts using jlink that were cobbled together by Lord Brimstone.
