### ISSUE TITLE
Lamia Sacred archers are too expensive and useless

### ISSUE THREAD

**Issue by smartwdf** [elmokki/nationgen#1043]
my 4/5 randomly generated lamian nations have sacred rangers. they are basically too expensive and stats are average.
![20190126084941_1](https://user-images.githubusercontent.com/31568199/51790524-69a20380-214b-11e9-8bcf-8b839884e5f8.jpg)
![20190126084955_1](https://user-images.githubusercontent.com/31568199/51790525-6ad33080-214b-11e9-8772-970183a2ae79.jpg)
![20190126085010_1](https://user-images.githubusercontent.com/31568199/51790526-6c045d80-214b-11e9-95cc-cbc6e30c17c4.jpg)
![20190126085025_1](https://user-images.githubusercontent.com/31568199/51790528-6d358a80-214b-11e9-92d8-2e2a6d70493f.jpg)
normal lamia archers appear to have the same problem, who will pay 30 gold for a shortbow/crossbow?

**Comment by Ealb** [comment]
It's probably reasonable to make lamias much less inclined to have sacred archers than other amazons. Shapechange filiters aren't normally given to ranged units, so it's in keeping with that idea.

That last one isn't normal, BTW: it's an elite, and elites generally cost more than line troops and less than sacreds.

As far as overall balance goes, I'm not going to drop lamia archers below their baseline racial gcosts. I might try to make archers more inclined to be militia-tier for them, though, which would pull down their cost at the expense of some of their stats.

**Comment by Althaea-Dominions** [comment]
Seems to me like giving them a shot at (or guarantee of) poison bows might make sense as well. Right now they just use the generic set of human bows.

**Comment by Ealb** [comment]
That's actually a good point, and it's essentially how I dealt with overpriced/undervalued Dustwalker archers. Well, that and better sidearms.

**Comment by Ealb** [comment]
So the tentative way forward with this is to make lesser lamia archers always use poison short bows, poison composite bows, or normal long bows (with elites/sacreds also having a chance to use poison slings, viper bows (stun and bite you), constrictor bows (stun and strangle you), or howling bows (à la Ancestor Vessels)). The sidearm list was narrowed to heavier weapons, but I might roll that back, as I gave all lesser lamia archers a claw attack in addition to whatever else they have. Incidentally and in keeping with that, lesser lamia mages get a lifedrain attack in addition to whatever else they have.
