### ISSUE TITLE
Merrow only filter supposedly breaks mod

### ISSUE THREAD

**Issue by elmokki** [elmokki/nationgen#1064]
02.42] Saranea: hey there, about natgen, i genned a 25 seed with "only" marrow as an item
[02.42] Saranea: -- Generated with version 0.7.0-RC9.
-- Generation setting code: 4
-- Nation seeds generated with seed -5376508820525165319.
-- Nation 120: Phealachinn generated with seed 7829167070028119665
-- Nation 121: Osnaig generated with seed 3424657289169761417
-- Nation 122: Laphha generated with seed -8556066321123927496
-- Nation 123: Fheinn generated with seed -6469642885009006591
-- Nation 124: Fairidh generated with seed 7747365177922825201
-- Nation 125: Foithinn generated with seed 4247785352353641047
-- Nation 126: Chlurhoainn generated with seed 7554835164943428251
-- Nation 127: Baingan generated with seed 2027684645418593231
-- Nation 128: Broiggartha generated with seed -4703015670436881584
-- Nation 129: Ceasdar generated with seed 3312440762681248691
-- Nation 130: Chan na Coille generated with seed -1910670230443902235
-- Nation 131: Sannar generated with seed -5596968961742883223
-- Nation 132: Ceas na Coille generated with seed -6463341151143023752
-- Nation 133: Phealdb generated with seed -8873131572949491220
-- Nation 134: Laphdar generated with seed 4551872184567461167
-- Nation 135: Fhuigh generated with seed -1622192214501946812
-- Nation 136: Fheha generated with seed 7790402995202508393
-- Nation 137: Ceasich generated with seed 2389813357448850791
-- Nation 138: Fhuamigh generated with seed -4743494983256529867
-- Nation 139: Achich generated with seed -7441055335864493784
-- Nation 140: Sannidh generated with seed -304591132187670963
-- Nation 141: Ailbasagh generated with seed 2277178517634937574
-- Nation 142: Changan generated with seed -2972893729479274616
-- Nation 143: Phealinn generated with seed 1346917348774401813
-- Nation 144: Broigigh generated with seed 1081635097363374728
[02.42] Saranea: those are the seeds

Here is related picture: https://cdn.discordapp.com/attachments/568234833688395782/568236587708579841/Unbenannt.JPG

**Comment by elmokki** [comment]
https://cdn.discordapp.com/attachments/568234833688395782/568236829522919454/Unbenannt.JPG

This is the error if you go to create a god or something.

**Comment by Ealb** [comment]
I'm failing to reproduce it. Based on the second error and the sheer number of errors, I'm rather inclined to assume they have one or more other mods running.

**Comment by Ealb** [comment]
Spoke w/user, they can't reproduce either.
