### ISSUE TITLE
Double body armor on cyclops

### ISSUE THREAD

**Issue by elmokki** [elmokki/nationgen#1067]
A cyclops someone generated with 0.7.0 RC9 apparently has two body armors instead of - I assume -  a helmet. @Ealb might be able to fix this based on the unit graphic here alone: https://cdn.discordapp.com/attachments/386535818879172609/569931645579427840/unknown.png

However, seed is -6485769561684748541 with setting code 8.

**Comment by Ealb** [comment]
Flashfire fixed it in January with #1042 . Ugh, we need to get an update out. I'll tie off some of my numerous incomplete content pieces and will tentatively aim for this coming weekend.
