### ISSUE TITLE
Commander names

### ISSUE THREAD

**Issue by Ealb** [elmokki/nationgen#109]
I'm seeing some e.g. Lizard Hammerers led by a Hammerer, or Spear Bandits led by a Spearman (305775971 and -1293911936 with gen options 2 (LA), respectively). It's not happening consistently, but it is happening relatively frequently - maybe 1/5 nations have commanders with simple troop names. I can kinda sorta maybe see a case for this happening, but at the same time it looks pretty odd and at first blush I'd honestly assume it's a bug.

**Comment by elmokki** [comment]
Interestingly before I merged master to my branch the first seed gave me a "Hammerer Commander" instead of Hammerer. Time to investigate.

**Comment by elmokki** [comment]
There just was a plain bug with #generic using weaponnames instead of weaponprefixes

**Comment by elmokki** [comment]
Also, unrelated, are you fine with removal of the national nameparts?

I thought Blablaish Heavy Sword Infantry or Heavy Sword Infantry of Blabla is too long (even if you can theoretically get Agarthan Heavy Sword Infantry now) so I scrapped it but added the race naming for secondary races whose name is different from the main race.

**Comment by Ealb** [comment]
I kinda miss it, since it makes it that much less common to see the nation name, but it's not a huge loss. I would say that it might be nice to see it occasionally, but I'm not sure how that could happen without it seeming really weird among the non-national names. Perhaps it could be used with priests or scouts, as they have comparatively generic names, but again, it's not drastic to see it gone - it's just different.

**Comment by elmokki** [comment]
scouts and priests could indeed be a good place for those
