### ISSUE TITLE
Scouts don't seem to be considering #basechance for poses

### ISSUE THREAD

**Issue by Ealb** [elmokki/nationgen#112]
Based on test nations and also from looking in generateScout (the for loop at line 68, I think), it seems as though scout poses are being chosen deterministically w/o consideration of chanceincs. This is leading to oriental hoburgs with standard European scouts.

I tried a quick fix of replacing said for loop with:

List<Pose> possibleposes = new ArrayList<Pose>();
for(Pose p2 : race.poses)
{
	if(p2.roles.contains(posename) && p2.getItems("weapon").contains(weapon))
	possibleposes.add(p2);
}
			
if(possibleposes.size() > 0)
	p = Pose.getRandom(random, chandler.handleChanceIncs(race, posename, possibleposes));

...but I merely went from always getting European scouts to only getting them maybe half the time. I could probably muddle through and find where my coding is mistaken, but I'd not be surprised if you could immediately see the solution.

**Comment by elmokki** [comment]
I would suspect that the reason it still gives european scouts 50% of the time is that the code gets a weapon first and then searches for poses using that weapon. Good for when it was written, but horrible for now.

The ways to solve this are:
1. Ignore weapon before pose is selected and just give a good enough weapon if the pose doesn't have suitable stuff 
2. Select a pose first and then loop and reselect poses until you have a weapon or there have been enough tries

I think I'm gonna go with #1 and add some scout/spy/assasin generation parameters. I mean, after all, whoever makes content can choose whether to allow assassins or maybe whether to allow assassins to have offhands etc.
