### ISSUE TITLE
#copystats in item commands

### ISSUE THREAD

**Issue by lord-brimstone** [elmokki/nationgen#1129]
`#copystats` is not currently fully supported for use as a command in item definitions due to how commands are applied.  Currently, a set of default stats exists in the command list prior to copystats being added, making any further stat commands that match the default stat commands update the existing command, and since it comes before copystats in the command list, the command won't actually end up applying to the unit.

I'm not exactly sure how to go about handling this.  Do we want `#copystats` on a slot item make it so that the race and pose commands shouldn't apply?  It currently doesn't apply race and pose commands if the unit is a `ShapeChangeUnit` -- is this a similar situation?  Another option would be to purge all prior commands when `#copystats` is encountered.

I think in addition to deciding on the above, the order of commands coming from different slots might be considered -- should we make sure the commands on the `basesprite` item always come before any other slot item commands?  I am assuming we would only ever want to `#copystats` on the `basesprite` and not any other slot.  Or maybe it should be flexible and check for any slot containing `#copystats` and prioritize that slot first?

Also to consider -- all the other commands from modding section 7.3:
`#clear`
`#clearweapons`
`#cleararmor`
`#clearmagic`
`#clearspec`
`#copyspr`

**Comment by lord-brimstone** [comment]
After speaking with Eel, we decided that all `#copystat` and `#clearX` commands should be pulled to the top of the list before processing, then the commands will be processed as normal.

**Comment by elmokki** [comment]
This seems very sensible.

**Comment by Ealb** [comment]
The basic conclusion I came to after LB forced me to think about this thoroughly is that anyone making things for NationGen should treat #copystats as a command of last resort to duplicate single effects that are not currently moddable. Given that, we shouldn't care at all about anything but the special attributes and should redefine everything else to overwrite the other stats of units we're copying. In that case, we can conseptually view the sequence [#copystats/#clearweapons/#cleararmor/#clearmagic] as a unique and unitary wildcard/placeholder command and we still need to define absolutely everything else just like we'd define a unit w/o a copystats.
