### ISSUE TITLE
Chargedbody filter has onebattlespell geyser and NOT charge body

### ISSUE THREAD

**Issue by djmcgill** [elmokki/nationgen#1145]
```
#new magefilter
#name "chargedbody"
#basechance 0
#command "#onebattlespell 500"
#chanceinc "personalmagic air 0.5"
#description "has charged body"
#end
```
Unless something weird going on, spell 500 is geyser, and 592 is charged body
![image](https://user-images.githubusercontent.com/1290757/83272040-95f7e500-a1c2-11ea-88c7-21a8fe63e1f3.png)

**Comment by Ealb** [comment]
Thanks, fixed.
