### ISSUE TITLE
Offhands still ignoring #troopweapon

### ISSUE THREAD

**Issue by Ealb** [elmokki/nationgen#116]
I'm still seeing some units generate with a spear plus an offhand even if the spear is tagged #troopweapon - I tried tagging the offhands as #troopweapon as well but had no better luck. Haven't code-dived yet though.

![preview_107_kamahaburg](https://cloud.githubusercontent.com/assets/12613576/8577307/cf62e552-2575-11e5-80f2-9b3fde0155a2.png)

(Seed 2009243981 (2/LA) using the current state of Ealb/nationgen - oriental hoburgs are weighted  very heavily.)

(This also shows another quirk that has arisen since the new troop generation was implemented - the sacred troops have an elite kabuto, while the commander generated from them has a normal kabuto. Commanders made from elites appear to at least usually (I think actually always) use the non-elite version of any elite items their troops have; i.e., it appears that if an elite troop has "foo_elite" in slot foo, by preference a commander derived from that troop will if possible fill slot foo with an item that has #eliteversion "foo_elite".)

**Comment by elmokki** [comment]
#Troopweapon applies to mages and priests only. The units in question aren't such. Still interesting though.

**Comment by elmokki** [comment]
It was caused by having no shields available to the pose. It defaulted to using whatever offhand in such case.
