### ISSUE TITLE
Okleader vs okayleader typo

### ISSUE THREAD

**Issue by djmcgill** [elmokki/nationgen#1160]
Having leadership 40 is the default so I don't know how much this bug actually matters but from the manual:
> #okleader
> Leadership value 40. This is the default value and it is the standard for non-elite commanders.

vs
![image](https://user-images.githubusercontent.com/1290757/88428754-62fe5600-cded-11ea-8051-06def0a466ac.png)

**Comment by geepope** [comment]
This was corrected in #1161.
