### ISSUE TITLE
Please fix the errors for Dominions 6

### ISSUE THREAD

**Issue by RiritoXXL** [elmokki/nationgen#1197]
![Dominions6_I3NJFTHOGL](https://github.com/user-attachments/assets/27dddd84-d45e-4293-b4e7-b390f87a0188)

![Dominions6_ImQSkyHkmw](https://github.com/user-attachments/assets/8c9e738b-c7d2-4638-a58f-57e1ff8ca603)

Please fix the errors for Dominions 6... Thanks!!!

**Comment by elmokki** [comment]
Can you please provide the seed? Open the .dm file in notepad and from the start share something like this:

-- NationGen - nationgen_lumbula
-----------------------------------
-- Generated with version 0.7.0-RC12.
-- Generation setting code: 1
-- Nation seeds generated with seed 4298298204790918891.
-- Nation 120: Lumbula generated with seed -9083164144942290263
-----------------------------------

**Comment by elmokki** [comment]
Thank you!

**Comment by RiritoXXL** [comment]
You're Welcome!

**Comment by RiritoXXL** [comment]
> Thank you! Seems like you are using 0.8.0. The newest release is 0.8.6. It may have fixed this issue.

nationgen.jar is version 0.8.0 not 0.8.6

**Comment by elmokki** [comment]
> > Thank you! Seems like you are using 0.8.0. The newest release is 0.8.6. It may have fixed this issue.
> 
> nationgen.jar is version 0.8.0 not 0.8.6

Ah, you are correct. The version number has not been updated in the source code.

**Comment by RiritoXXL** [comment]
> > > Thank you! Seems like you are using 0.8.0. The newest release is 0.8.6. It may have fixed this issue.
> > 
> > 
> > nationgen.jar is version 0.8.0 not 0.8.6
> 
> Ah, you are correct. The version number has not been updated in the source code.

@danieldelpercio please update to 0.8.6 jar file... Thanks!!!

**Comment by RiritoXXL** [comment]
> > > Thank you! Seems like you are using 0.8.0. The newest release is 0.8.6. It may have fixed this issue.
> > 
> > 
> > nationgen.jar is version 0.8.0 not 0.8.6
> 
> Ah, you are correct. The version number has not been updated in the source code.

How to Compile this program?! Java Is Installed, All Src Codes of JDK Installed!!!

**Comment by elmokki** [comment]
> > > > Thank you! Seems like you are using 0.8.0. The newest release is 0.8.6. It may have fixed this issue.
> > > 
> > > 
> > > nationgen.jar is version 0.8.0 not 0.8.6
> > 
> > 
> > Ah, you are correct. The version number has not been updated in the source code.
> 
> How to Compile this program?! Java Is Installed, All Src Codes of JDK Installed!!!

The .jar is 0.8.6. The number is wrong, but file is correct.

![image](https://github.com/user-attachments/assets/8f13c01b-4add-4ba4-82fc-6202930202a6)

**Comment by elmokki** [comment]
Also, are you trying it with Dominions 6 or Dominions 5?

**Comment by RiritoXXL** [comment]
> Also, are you trying it with Dominions 6 or Dominions 5?

Dominions 6

**Comment by RiritoXXL** [comment]
> > Also, are you trying it with Dominions 6 or Dominions 5?
> 
> Dominions 6

On Dominions 5 all worked!!! :D

**Comment by elmokki** [comment]
> > > Also, are you trying it with Dominions 6 or Dominions 5?
> > 
> > 
> > Dominions 6
> 
> On Dominions 5 all worked!!! :D

0.8.0 and higher should be Dominions 6. So there could be something broken that is not immediately visible.

**Comment by RiritoXXL** [comment]
> > > > Also, are you trying it with Dominions 6 or Dominions 5?
> > > 
> > > 
> > > Dominions 6
> > 
> > 
> > On Dominions 5 all worked!!! :D
> 
> 0.8.0 and higher should be Dominions 6. So there could be something broken that is not immediately visible.

Understand!

**Comment by danieldelpercio** [comment]
> ```
> -- NationGen - nationgen_keep_of_eternal_rest
> -----------------------------------
> -- Generated with version 0.8.0.
> -- Generation setting code: 2
> -- Nation seeds generated with seed 3820442309853652135.
> -- Nation 150: Ishasa generated with seed -173774517100615216
> -- Nation 151: Arcoope generated with seed -2471279886209939167
> -- Nation 152: Y'golondaiiggua generated with seed 794756757401855288
> -- Nation 153: Yog-Saphoth generated with seed 784264089217916192
> ```

I tried generating 5 nations with this seed and they all loaded into Dominions without any issue.

**Comment by RiritoXXL** [comment]
> > ```
> > -- NationGen - nationgen_keep_of_eternal_rest
> > -----------------------------------
> > -- Generated with version 0.8.0.
> > -- Generation setting code: 2
> > -- Nation seeds generated with seed 3820442309853652135.
> > -- Nation 150: Ishasa generated with seed -173774517100615216
> > -- Nation 151: Arcoope generated with seed -2471279886209939167
> > -- Nation 152: Y'golondaiiggua generated with seed 794756757401855288
> > -- Nation 153: Yog-Saphoth generated with seed 784264089217916192
> > ```
> 
> I tried generating 5 nations with this seed and they all loaded into Dominions without any issue.

Okay...

**Comment by RiritoXXL** [comment]
Nevermind, it is bug with Debug Mod(Dominions 5 Mod)...

**Comment by RiritoXXL** [comment]
![Dominions6_XDI6kRCTG7](https://github.com/user-attachments/assets/ffcdd789-e6c1-4c1a-ac09-d34b9599fe8e)

![mspaint_RrTyAGyCzg](https://github.com/user-attachments/assets/d668c266-8f35-4707-93c3-2842fa989892)

@danieldelpercio @elmokki please help me with this error!!! :(

**Comment by elmokki** [comment]
> ![Dominions6_XDI6kRCTG7](https://private-user-images.githubusercontent.com/179821354/370173539-ffcdd789-e6c1-4c1a-ac09-d34b9599fe8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNjgxNjEsIm5iZiI6MTcyNzE2Nzg2MSwicGF0aCI6Ii8xNzk4MjEzNTQvMzcwMTczNTM5LWZmY2RkNzg5LWU2YzEtNGMxYS1hYzA5LWQzNGI5NTk5ZmU4ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNFQwODUxMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NTZlMDQ2OTcxMjE1NjU4OTUwZTg2NjA2NWYxMDdlZjQwMzllNTE1OTk5OGMwZDg2YmMyY2IzMTM5YjFmNmQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ETwVMGWovJH9nWqWj5Np4TNWEVKEVm1cqy2Cl1fCz3E)
> 
> ![mspaint_RrTyAGyCzg](https://private-user-images.githubusercontent.com/179821354/370173577-d668c266-8f35-4707-93c3-2842fa989892.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNjgxNjEsIm5iZiI6MTcyNzE2Nzg2MSwicGF0aCI6Ii8xNzk4MjEzNTQvMzcwMTczNTc3LWQ2NjhjMjY2LThmMzUtNDcwNy05M2MzLTI4NDJmYTk4OTg5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNFQwODUxMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMDgxOTE2NDllMWZjZjdkY2RlODBjMTMwNmQ3OWUyOWNhYWMzNzM3NTNjODY2N2YxMjZmMGI0ZWY0NWM3YzZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.OTe4oqQDfbtGAmvFZOofqyVAJvneTaJs3ucpkiaVh7M)
> 
> @danieldelpercio @elmokki please help me with this error!!! :(

Please give the seed like previously. And also please the .tga file.

Paint cannot open those files, but GIMP, for example, can.

**Comment by RiritoXXL** [comment]
```
-- NationGen - nationgen_keep_of_eternal_rest
-----------------------------------
-- Generated with version 0.8.0.
-- Generation setting code: 2
-- Nation seeds generated with seed 3820442309853652135.
-- Nation 150: Ishasa generated with seed -173774517100615216
-- Nation 151: Arcoope generated with seed -2471279886209939167
-- Nation 152: Y'golondaiiggua generated with seed 794756757401855288
-- Nation 153: Yog-Saphoth generated with seed 784264089217916192
-----------------------------------
```

**Comment by RiritoXXL** [comment]
> ```
> -- NationGen - nationgen_keep_of_eternal_rest
> -----------------------------------
> -- Generated with version 0.8.0.
> -- Generation setting code: 2
> -- Nation seeds generated with seed 3820442309853652135.
> -- Nation 150: Ishasa generated with seed -173774517100615216
> -- Nation 151: Arcoope generated with seed -2471279886209939167
> -- Nation 152: Y'golondaiiggua generated with seed 794756757401855288
> -- Nation 153: Yog-Saphoth generated with seed 784264089217916192
> -----------------------------------
> ```

github doesn't support .tga file upload!!! :<

**Comment by RiritoXXL** [comment]
> ![Dominions6_XDI6kRCTG7](https://private-user-images.githubusercontent.com/179821354/370173539-ffcdd789-e6c1-4c1a-ac09-d34b9599fe8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNzExMjAsIm5iZiI6MTcyNzE3MDgyMCwicGF0aCI6Ii8xNzk4MjEzNTQvMzcwMTczNTM5LWZmY2RkNzg5LWU2YzEtNGMxYS1hYzA5LWQzNGI5NTk5ZmU4ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNFQwOTQwMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZTMzYmJmNTYyNjJhMzcwNzA4MjY2NmYyMGEzNWYyOTRjM2JmZmExNDA2Nzc4MDliMzkxNDE1NWE2ZjhlMGI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.z_PSn8BFfbvqw4d_6ZzaPRObhMABsr1Q7qre7hIhgd4)
> 
> ![mspaint_RrTyAGyCzg](https://private-user-images.githubusercontent.com/179821354/370173577-d668c266-8f35-4707-93c3-2842fa989892.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNzExMjAsIm5iZiI6MTcyNzE3MDgyMCwicGF0aCI6Ii8xNzk4MjEzNTQvMzcwMTczNTc3LWQ2NjhjMjY2LThmMzUtNDcwNy05M2MzLTI4NDJmYTk4OTg5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNFQwOTQwMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YzFlMzQzODY0ODRiZjc5YWZlYWFkYzc3MGZiNDdjMzQ1MDM1ZmI4M2U5ZGQ1YmI3NzQzYzM2NGE2MmZmNzAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jDQa6SDIebu9dz7iAPuy7diiFUNT1sIfkZGemO3rI38)
> 
> @danieldelpercio @elmokki please help me with this error!!! :(

Directory is written incorrectly...

**Comment by elmokki** [comment]
> > ![Dominions6_XDI6kRCTG7](https://private-user-images.githubusercontent.com/179821354/370173539-ffcdd789-e6c1-4c1a-ac09-d34b9599fe8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNzExMjAsIm5iZiI6MTcyNzE3MDgyMCwicGF0aCI6Ii8xNzk4MjEzNTQvMzcwMTczNTM5LWZmY2RkNzg5LWU2YzEtNGMxYS1hYzA5LWQzNGI5NTk5ZmU4ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNFQwOTQwMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZTMzYmJmNTYyNjJhMzcwNzA4MjY2NmYyMGEzNWYyOTRjM2JmZmExNDA2Nzc4MDliMzkxNDE1NWE2ZjhlMGI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.z_PSn8BFfbvqw4d_6ZzaPRObhMABsr1Q7qre7hIhgd4)
> > ![mspaint_RrTyAGyCzg](https://private-user-images.githubusercontent.com/179821354/370173577-d668c266-8f35-4707-93c3-2842fa989892.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNzExMjAsIm5iZiI6MTcyNzE3MDgyMCwicGF0aCI6Ii8xNzk4MjEzNTQvMzcwMTczNTc3LWQ2NjhjMjY2LThmMzUtNDcwNy05M2MzLTI4NDJmYTk4OTg5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNFQwOTQwMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YzFlMzQzODY0ODRiZjc5YWZlYWFkYzc3MGZiNDdjMzQ1MDM1ZmI4M2U5ZGQ1YmI3NzQzYzM2NGE2MmZmNzAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jDQa6SDIebu9dz7iAPuy7diiFUNT1sIfkZGemO3rI38)
> > @danieldelpercio @elmokki please help me with this error!!! :(
> 
> Directory is written incorrectly...

Actually yes! Nicely spotted. Are you running this on Dominions 5 or Dominions 6 now?

Can you find a line in the .dm that starts with #flag? Something like "#flag "nationgen_lumbula/120-lumbula/flag.tga"?

**Comment by RiritoXXL** [comment]
> Actually yes! Nicely spotted. Are you running this on Dominions 5 or Dominions 6 now?

Runned on Dominions 6, Crushed with FSA: Bad Image(maybe bc directory is written incorrectly)... Dominions 5 all worked!!!

Line in the .dm starts with #flag:
```
#flag "nationgen_desert_of_stories/150-kathan/flag.tga"
```

**Comment by elmokki** [comment]
> > Actually yes! Nicely spotted. Are you running this on Dominions 5 or Dominions 6 now?
> 
> Runned on Dominions 6, Crushed with FSA: Bad Image(maybe bc directory is written incorrectly)... Dominions 5 all worked!!!
> 
> Line in the .dm starts with #flag:
> 
> ```
> #flag "nationgen_desert_of_stories/150-kathan/flag.tga"
> ```

Thanks. I assume Dominions 6 has changed how reference directories. However, I assume the mods have worked for other people, so it might be a bit more complicated.

**Comment by RiritoXXL** [comment]
> > > Actually yes! Nicely spotted. Are you running this on Dominions 5 or Dominions 6 now?
> > 
> > 
> > Runned on Dominions 6, Crushed with FSA: Bad Image(maybe bc directory is written incorrectly)... Dominions 5 all worked!!!
> > Line in the .dm starts with #flag:
> > ```
> > #flag "nationgen_desert_of_stories/150-kathan/flag.tga"
> > ```
> 
> Thanks. I assume Dominions 6 has changed how reference directories. However, I assume the mods have worked for other people, so it might be a bit more complicated.

or the developers themselves just screwed up with the directory...

**Comment by elmokki** [comment]
> > > > Actually yes! Nicely spotted. Are you running this on Dominions 5 or Dominions 6 now?
> > > 
> > > 
> > > Runned on Dominions 6, Crushed with FSA: Bad Image(maybe bc directory is written incorrectly)... Dominions 5 all worked!!!
> > > Line in the .dm starts with #flag:
> > > ```
> > > #flag "nationgen_desert_of_stories/150-kathan/flag.tga"
> > > ```
> > 
> > 
> > Thanks. I assume Dominions 6 has changed how reference directories. However, I assume the mods have worked for other people, so it might be a bit more complicated.
> 
> or the developers themselves just screwed up with the directory...

Since it opens on Dom5 but not Dom6, it's likely Illwinter's changes breaking things.

**Comment by RiritoXXL** [comment]
> > > > > Actually yes! Nicely spotted. Are you running this on Dominions 5 or Dominions 6 now?
> > > > 
> > > > 
> > > > Runned on Dominions 6, Crushed with FSA: Bad Image(maybe bc directory is written incorrectly)... Dominions 5 all worked!!!
> > > > Line in the .dm starts with #flag:
> > > > ```
> > > > #flag "nationgen_desert_of_stories/150-kathan/flag.tga"
> > > > ```
> > > 
> > > 
> > > Thanks. I assume Dominions 6 has changed how reference directories. However, I assume the mods have worked for other people, so it might be a bit more complicated.
> > 
> > 
> > or the developers themselves just screwed up with the directory...
> 
> Since it opens on Dom5 but not Dom6, it's likely Illwinter's changes breaking things.

That's for sure

**Comment by elmokki** [comment]
This should be fixed in the next version

**Comment by RiritoXXL** [comment]
> This should be fixed in the next version

thanks very much my friend :)
