### ISSUE TITLE
SacredGenerator is using inconsistent DW tags

### ISSUE THREAD

**Issue by Ealb** [elmokki/nationgen#126]
Not a huge issue since I can just add the redundant tag in the particular cases I'm looking at, but currently SG is the only method using "#always_dw", and at the same time it doesn't appear to be considering "#dwchancebonus `<bonus`>". For consistency, one of us should probably change that eventually, but again, it seems like it's low priority given the data definitions we currently have.

**Comment by Ealb** [comment]
Okay, scratch that. I think I need to muddle through this after all, as using #always_dw gives me spears and offhands, while still not letting me trick the system into DWing two 2h weapons, even if I use mainhand=(id -1/needs specialweapon foo), specialweapon=(id actual_id_of_foo) - this does work for normal troops, but for sacreds they never DW.

(This is in the context of having medium/large clockworks DWing 2h weapons, but the vanilla game actually has a few precedents; i.e., the prophetform of Abysian warlords who run around with 2 battleaxes)

**Comment by elmokki** [comment]
I'm fixing it already.

**Comment by elmokki** [comment]
...and I actually independently thought of allowing non-standard dualwielding too

**Comment by elmokki** [comment]
The commit comment gives a comprehensive documentation of stuff. 

#always_dw by the way just ignored everything else.

**Comment by elmokki** [comment]
...and there's a debug message left in code. I'll remove that and add a small extra feature that may be of use with giants eventually.
