### ISSUE TITLE
Hoburg cohesion (again), ambiguous debug message, maybe #needs problem

### ISSUE THREAD

**Issue by Ealb** [elmokki/nationgen#154]
I have no idea what changed, but hoburgs are severely incohesive again. They're probably worse than before, actually. Some of it may be that I further fleshed out their gearset so incohesion is more obvious, but even just looking at the presence of different basesprites or mixing of oriental/standard poses it looks a lot less cohesive than before for no obvious reason.

There's also some debug messages that are getting spammed fairly heavily. I didn't track down where they were, as much as anything because I figure you'd actually know where to look w/o stepping through the program in debug (which is what I'd have to do, based on my failure to track it down by looking at the code or searching). The messages I've seen are "#idealcold" and "#tradecoast", they show up during nation generation, and it looks like 30-50 of them show up at a time.

I'm also having issues with #needs on the hoburgs' shirts, but I'm kinda assuming that's a dumb data-driven mistake on my part arising from fatigue.

If the above issues can be resolved or determined to be non-issues, I'd say just disable the special weapons on the big clockworks and I'll fix that for 0.6.1 since I still haven't had a chance to do that.

**Comment by elmokki** [comment]
The debug message I thought I removed. I suppose I was too tired as well. I'll give a look to hoburgs.

**Comment by elmokki** [comment]
Okay. Troop generation debug breaken to parts:

Hoburg - [agrarian, boreal, default]:

 {[infantry, scout] (boreal infantry)=0.1, [infantry, scout] (oriental infantry)=0.1, [infantry, scout] (stealthy boreal infantry)=0.05, [infantry, scout] (stealthy oriental infantry)=0.05} 

-> [infantry, scout] (stealthy oriental infantry)

With these probabilities after chanceincs it is no wonder the nation has some oriental units. I will investigate.

**Comment by elmokki** [comment]
This is the issue:

    #themeinc theme boreal *1000
    #themeinc theme abysian *0.001

Poses have both themes so they cancel each other out. I changed the *0.001 #themeincs to thisitemtheme instead.

**Comment by Ealb** [comment]
Ugh, yes, that looks about right. I was trying to be quite clever and was
instead merely quite tired. A fine testimony to the value of knowing when
to stop, go to bed, and revisit the problem when better-rested...
