### ISSUE TITLE
SpecialCommanderGenerator

### ISSUE THREAD

**Issue by elmokki** [elmokki/nationgen#156]
Now with themes - specifically the unit level filter themes - this becomes a bit more viable.

Basically a wolfherd would get filter with #themeinc theme herder *100 and chances are it would be enabled only for certain races anyway. Then the filter could specifiy a pose to use either at a general #poserole level or at a specific #posename level (posename should override poserole if pose of the name is found). Some poses would just be mages - especially for tax collector type units I think most races have pretty good robes.  A few can concieveably be normal infantry with suitable style of armor - like there's a blood hunter and patroller defined.

I think there should also be a chance to give some of these to normal commanders. For example substantial siege and patrol bonuses are something a normal commander might viably get.

**Comment by elmokki** [comment]
Now, general ideas for graphics here are:

1. Tagging some mage gear for cultist. There's definitely going to be some imp summoners or reanimators which can just be mages with priority on certain gear. 
2. Peasant gear for wolf/frog/goatherd. Probably a suitable hat and so ripped from wolfherd will do.
3. Tagging some mage gear for administrative. At least humans and human gear users tend to have those T'ien C'hi robes which fit excellently to tax collectors and pd trainers.

The main question here is whether some races should just be excluded from many of the specialcommander filters due to lack of graphics or whether they should get them with somewhat generic geared commanders.

I think that at the very least something like the elves will get special commanders more rarely and something like agrarian hoburgs will get them very often.

**Comment by Ealb** [comment]
I'd lean towards the second option. E.g., the filter "#wantstype helmet cultist", for a lack of better terms.

**Comment by elmokki** [comment]
#themeincs work in unit filters so just #themeinc cultist *100 or something should be pretty good
