### ISSUE TITLE
Commander/priest prices

### ISSUE THREAD

**Issue by Ealb** [elmokki/nationgen#173]
Something is screwed up with basic commander and priest prices. Mage prices seem normal, but to cite an extreme case, I've seen sacred commanders who cost less than the sacreds they're based on.

E.g. Avatep generated with seed -1005035832 (0.6.2, settings 0)

I'll see if I can figure out what's going on.

**Comment by elmokki** [comment]
My command writeorder change moved Unit-class commands earlier. This was a horrible idea since the only place where those are absolute is ShapeChangeUnit. Reverting this and writing a workaround for ShapeChangeUnits.
