### ISSUE TITLE
Lockslots/non-base theme-limited slots

### ISSUE THREAD

**Issue by Ealb** [elmokki/nationgen#181]
I've been trying to do random nation-wide pigments for ichtyids, and have had no luck. I haven't really dived into the code so far, but based on output it somewhat seems like themeincs aren't being considered for a #generateitem slot like "scales". Looking at the code for lockslot, my original attempt to use lockslot was doomed to failure since that only works for hands, legs, basesprite, and shadow. However, extremely high themes on scale entries also leads to extremely heterogeneous fish. Likewise, integrating the scales into basesprites and locksloting those doesn't seem to work any better.

I'll upload my current mess into my fork in case the solution is obvious.

**Comment by elmokki** [comment]
The reason your #lockslot doesn't work is that the slot for bases is "basesprite", not "base".

**Comment by elmokki** [comment]
I'll still investigate #generateitem, though a quick glance at code says there should be no reason for it to not work with themes.

**Comment by elmokki** [comment]
Yeaah, this is very obvious:
``#themeinc common_pigment *10000´´
should be
´´#themeinc theme common_pigment *10000´´

**Comment by Ealb** [comment]
Ha, yeah, fatigue does bad things to me. You're right on both counts. I just realized that while I caught the problem with using base instead of basesprite shortly before posting this issue, when I fixed it and tested, I forgot to save. The text editor was still sitting on my desktop, open but unsaved three hours later. As for themeinc theme... ouch. Just ouch.

Almost three days, on and off, I've been trying to figure out what was wrong with those scales. Sometimes my ability to make dumb mistakes and then just stubbornly not see what's wrong with them is quite impressive, sigh.

**Comment by Ealb** [comment]
Okay, maybe I was less blind than I thought. Regardless of how messed up I managed to make the code I had before, after fixing it there still seems to be a problem with heterogeneity:

![preview_134_atlathia](https://cloud.githubusercontent.com/assets/12613576/8814814/d6c7edd8-2fde-11e5-995f-e44ab10ce2c7.png)

This is Atlathia generated with seed -721046220 from my latest upload. It's going the route of #generateitem 1 scales and #themeinc theme foopigment *1000, but still around half the units aren't getting what they should be. I'll take a look since it seems like a nice, clear example.

**Comment by Ealb** [comment]
Oh, geez, never mind. I forgot to add "scales" to the renderorder for scouts and non-elite troops. Wow. Yeah. Dumb, dumb, dumb.
