### ISSUE TITLE
0.6.5

### ISSUE THREAD

**Issue by Ealb** [elmokki/nationgen#211]
How much more stuff do we want to tie up before pushing out a new version? I don't think any of the current bugs/rebalancing are pressing, but I suppose it's still worth asking.

In re: content, I'm maybe 1/4-1/3 done with hoburg pod farmers - if I stay focused, they'll be done this weekend at the latest. They may be done tonight or tomorrow if nothing pops up to distract me.

**Comment by elmokki** [comment]
I don't have any concrete plans. Maybe a look at the shapeshifts that behave stupidly. Maybe special commanders if I can be arsed.

**Comment by elmokki** [comment]
Based on IRC there's a new nationgen game setting up. I think 0.6.5 warrants release today then. It's 16:18 my time and thus goal would be within 9 hours or so. I will try  to fix some more bugs before.

**Comment by Ealb** [comment]
It's unlikely that I can get anything meaningful done by then, but I'll take a stab at it if I can.

**Comment by elmokki** [comment]
0.6.5 is out.
