### ISSUE TITLE
Idea: Undead theme for various races

### ISSUE THREAD

**Issue by elmokki** [elmokki/nationgen#212]
By suitably recoloring sprites (ie making them paler) we could make an undead theme that makes all national units undead and pale. I tried this on humans but my recolor tries weren't good enough so I scrapped it.

I might try it again, but I also realized that this is also a major nerf to the nation so something more than slight magic resist boost and (nearly) guaranteed death magic would be needed to make it worthwhile. One of those things is reanimation, but that would need some code rethinking to be done properly so that it doesn't collide with nationfilters.

Nationwidefilters and nationfilters should probably just be made a more generic type themes that is handed out separately.

**Comment by Ealb** [comment]
Well, on a mostly-but-not-quite-entirely unrelated note, I took a long look at imperial/romanesque nations over the last few days, and I'm thinking it'd be pretty easy to make them since - when you look at the few examples where it's not hidden by tower shields - their armor is essentially the same as Abysian armor. So there's that.

**Comment by elmokki** [comment]
Yeah, I think some of the helmets are similar as well. The thing with those nations is that their gear will be a bit monotonous since there isn't that much stuff that makes sense. Though they could have a gladiator pose.

**Comment by Ealb** [comment]
...on that note, hoburgs now have an imperial theme, and hoburgbred thus have more distinctive armor, too. I swear this hoburg tangent of mine will end when I finish the vine themes...

**Comment by elmokki** [comment]
I thought you were making those for humans and maybe some other human size races, but oh well, hoburgs are hoburgs! I hope we'll see hoburg gladiators.

**Comment by Ealb** [comment]
Gladiators need some kind of functionality like #tag "fixedrescost 1" or suchlike to override calculated rescost. Probably wouldn't hurt to add parallel functionality for gcost if the other is added, for that matter.

**Comment by elmokki** [comment]
Probably just #adjustmentcommand or something that will always be resolved last

**Comment by elmokki** [comment]
This is such a random idea that it hardly is an issue.

**Comment by Ealb** [comment]
Ugh, this reminds me that I really need to set aside some time to twist my arm and attack some of my months-old issues instead of strictly making new stuff.

**Comment by Ealb** [comment]
Is there any easy way to proceedurally screw with brightness/contrast in Java? In Gimp, if you take a unit, desaturate it, recolor it to f8e0c8, and boost brightness/contrast to 60/50, you end up with something fairly close to Attentive Statues, which would work nicely for either a stone mage/sacred filter, or as a national PD unit for nations with a golemcult 5 or 10, much as MA Agartha has Attentive Statue PD.

E.g. base-game Sentinal ![sentinal](https://cloud.githubusercontent.com/assets/12613576/10860063/11406b66-7f3a-11e5-81c2-7fecdeb6f4ee.png) vs. gen'd Agarthan ![gen-agarthan](https://cloud.githubusercontent.com/assets/12613576/10860072/20e7366c-7f3a-11e5-99f1-5735ec9ca151.png) vs. gen'd lizard ![gen-lizard](https://cloud.githubusercontent.com/assets/12613576/10860078/2e0857f4-7f3a-11e5-9162-bda3f6bac022.png)

(Yes, this idea is *at least* as random as the undead nation filters stuff above.)

**Comment by elmokki** [comment]
There is a greyscale option for secondshapes and such (via just using #spr1 greyscale [extra darkness])!

I absolutely detest working with java image operations but those might be easy.

**Comment by elmokki** [comment]
...yeah, recolors that are used for recolormasks don't work consistently and my contrast/brightness ops made things black. This might warrant a new look later since essentially adding pose/race/filter commands to recolor/greyscale/recontrast/brighten any/all non-shadow slots totally does make sense.
