### ISSUE TITLE
Content merges: should I be dumping those into a 0.7.0 branch?

### ISSUE THREAD

**Issue by Ealb** [elmokki/nationgen#232]
...and/or should we be maintaining a 0.6.X branch for bugfixes, etc until then?

Basically, how do we need to change our merging habits in keeping with your versioning comments on the forum?

**Comment by elmokki** [comment]
The main idea was that _some_ versions should be such that people can expect them to be relatively bug free. Having those major version changes as such makes more sense than having random versions as such. That means that everything needs to be tested well, so just dump everything into current branches.

Once we start approaching enough content that we're happy with 0.7.0 release we should stop with more content and features and release 0.6.x or 0.7.0 release candidates or whatever and just concentrate on bugfixing those for a week or two depending on the scale of bugs.
