### ISSUE TITLE
Commands parsing added/subtracted args as Integers

### ISSUE THREAD

**Issue by Ealb** [elmokki/nationgen#237]
Is there a reason for this? I understand there could well be one, but it's not immediately obvious. I'm specifically referring to the constructor:

try
{
	oldarg = "" + (Integer.parseInt(oldarg) + Integer.parseInt(arg));
	old.args.set(i, oldarg);
}
catch(NumberFormatException e)
{
	System.out.println("FATAL ERROR: Argument parsing " + oldarg + " + " + arg + " on " + c.command + " caused crash.");
}

(The query relates to gladiators; for size-1 gladiators rcosts per item are often fractional, and my best idea of a solution to Dom's refusal to allow absolute rcosts to be set is to have each item assigned add a negative rcost modifier upon assignment so we'd end up with 1 + (gear rcost) - (gear rcost). Obviously, this doesn't work if Command arguments are being treated as Integers.)

**Comment by elmokki** [comment]
Most (probably all?) Dominions modding commands use integers. Arguments on commands are stored as strings. Converting to integer and then summing and converting back to string leaves it in a non-decimal format whereas doing the same with Double.parseDouble would result in 1 being 1.0 and probably causing issues when the game reads it.

We could write code to read every argument as double and if succesful convert to integer, but honestly, it's probably easier if you just add some code to unit.polish() to read something like #norcost from Generic.getAllUnitTags(u) and then calculate the correct resource cost to substract

Also, did you test just adding #rcost -100 to units and seeing how that works?

**Comment by Ealb** [comment]
Tragically, that leads to rcost 0. This is not a point that Dominions makes easy to address. 

Incidentally, I did test a .dm with #rcost -11.5 and it worked just as well as #rcost -12. I'll go ahead and muddle out an adjustment to adjustment cost, though, since it makes more sense to have the special case applied narrowly instead of broadly.
