### ISSUE TITLE
Bear/Werebear inconsistencies

### ISSUE THREAD

**Issue by elmokki** [elmokki/nationgen#238]
You'll probably see the forum post as well, but:

https://www.dropbox.com/s/3xazxemjxeowj75/Bear%20and%20shapshift%20bear.pdf?dl=0

So, in a nutshell:
- Great Bear only has claw while cavalry riding it has has claw and bite
- Werebear has claw and bite while werewovles have two claws

I think werebears don't need a second claw necessarily, but we need to tweak great bears to one direction or another.

**Comment by Ealb** [comment]
Well, per NG design philosophy, they should probably lose the bite. When the rider dies, they transform to a copy of id 694, which doesn't have a bite. OTOH, looking at id 2351 (werebear), I kinda wonder why 694 *doesn't* have a bite, unless it's for game balance reasons. 2351 is basically just 694 with its stats tweaked a bit higher... plus a bite. I could fairly easily be persuaded to give great bear secondshapes a bite, though in that case small bear secondshapes should probably get one too.

I'm disinclined to add a second claw to werebears for related reasons - vanilla werebears don't have one, and it helps keep werewolves and werebears distinct.

**Comment by elmokki** [comment]
I think that for game balance reasons those huge bears might warrant a second attack. It's not a huge change and them being used as mounts is a very good reason to change them.

**Comment by elmokki** [comment]
And yes, werebears don't need a second claw.
