### ISSUE TITLE
Superior/inferior PD as a national filter

### ISSUE THREAD

**Issue by Ealb** [elmokki/nationgen#250]
A peripheral area where some further distinction between nations could be found is by giving them better/worse PD, either in terms of numeric rations, quality of troops selected, or quality of commanders (i.e., get a low-tier priest or mage instead of generic commanders).

**Comment by elmokki** [comment]
Defining quality is a bit hard in the current code, but other than that it should be pretty easy. Currently amounts per 10 gold are affected by gold/res provided they are below/above certain setting defined tresholds. 

I guess the quality would probably be targeting higher resource units, penalizing amount less on resource cost and penalizing low resource cost more in unit selection.

**Comment by elmokki** [comment]
I think these militia defining setting commands are stupid as setting commands and should probably be moved to filter definable with defaults in settings.

Also, should target resource cost be average resource cost of the nation instead? Maybe.

**Comment by Ealb** [comment]
That's actually a good point. By NG standards, national PD for e.g. MA Ulm or Agartha would probably be worse than it is (I suspect MA Ulm would probably end up with wardogs). Targeting based on averages seems like a more sensible route, and that might even eliminate the need to add the #cannot_be_pd tag I was trying to implement for gladiators (though at the same time, gladiators are disproportionately good as PD, so the tag would probably still be justified).

**Comment by elmokki** [comment]
Feature added.
