### ISSUE TITLE
#strongmagicpatterns and hoburgs

### ISSUE THREAD

**Issue by elmokki** [elmokki/nationgen#252]
...should this be given to just agrarian and primitive hoburgs?

I mean, it doesn't do that much. It makes really magical primary mages way more likely (especially stuff that gives you reliable level 5 in a path)

If so, we need a minor chanceinc edit.

**Comment by Ealb** [comment]
That seems fine. I'll go ahead and make the change.

For your situational awareness, Desura logged my account out today, I don't remember the PW and the PW retrieval options don't seem to be working. This happened maybe two weeks ago and then I spontaneously found myself logged back in, but I don't expect that to happen again. So unless I make a new account (assuming that's still possible) or the prior miracle repeats itself, I can't post to Desura.

**Comment by Ealb** [comment]
For the record, my days of posting to Desura appear to be definitively done, as email PW recovery continues to fail to produce any results, and while setting up a new account was still possible, I need to do an email confirmation prior to posting... and like the PW recovery, that does strictly nothing. Just FYSA.

**Comment by elmokki** [comment]
Yeah. It's a shame since Desura is the most active forum still, but eventually people are going to move elsewhere anyay.

**Comment by Ealb** [comment]
Ha, decided to give it one more go, and *actually remembered my password*. But yeah, Desura's days look sharply numbered. Honestly, I'm surprised it's still up and running.
