### ISSUE TITLE
4.20 and explicitly bronze items

### ISSUE THREAD

**Issue by Ealb** [elmokki/nationgen#258]
As anticipated/dreaded, 4.20 introduced a whole lot more bronze weapons defined as such. I'll take a stab at getting the various weapon data files updated in the next couple of days. The weapon database will need updated too, ugh.

**Comment by elmokki** [comment]
We may be able to pull databases from the mod inspector once they are updated. I believe even the column names are the same, but the two columns I added (flyspr and animlength or something like that) need to be manually added to that for flysprites to appear for custom versions of projectile weapons.

**Comment by Ealb** [comment]
Oh, that's a good point - I'll probably wait until the mod inspector gets updated so I'm not figuring out weapon ids by trial and error.

**Comment by elmokki** [comment]
You can use control + i when viewing unit stats to get some debug data including equipment ids.

That said, database is still easier.

**Comment by Ealb** [comment]
On a related note, once I get my grubby little hands on a 4.20 spritedump, it looks like there'll be more good candidates to steal for Hellenic/classical/what-have-you humans.

**Comment by elmokki** [comment]
Okay, updating weapon.csv might be a bit harder than I thought. Both armor and weapon .csvs in the mod inspector lack few important things like armor protections or weapon being twohanded in addition to some minor ones. However, it is possible to write a piece of code that uses a few of the files there to construct suitable armors/weapons.csv files.

**Comment by Ealb** [comment]
I'm *mostly* done with this as of #267. I still need to create variant bronze weapons for a few races (which will be a good lead-in to central/Hellenic humans, assuming I have the discipline to push those out), and Caelians are as-yet unexamined in this regard.

**Comment by Ealb** [comment]
The overwhelming basics work for everything but armor is done as of #302, and the remaining work on armor and race-specific weapons has been assigned/denoted in more specific issues. The scope of work for this issue has been more than resolved at this point.
