### ISSUE TITLE
Now sacreds can only have springpower +1?

### ISSUE THREAD

**Issue by ahyangyi** [elmokki/nationgen#269]
Is it good to add springpower 25(like spring hawks) and springpower 50 (like the EA/MA T'ien Ch'i sacreds) as alternative levels of these seasonpower sacreds?

I felt the current "seasonpower +1" ones are a bit underwhelming...

**Comment by elmokki** [comment]
I had no idea the seasonal powers are percentual. 25% and 50% versions woudl make sense.

I thought they behaved simialrly to scale powers which I nerfed at some point because their levels were excessive.
