### ISSUE TITLE
Intermitantly not recognizing #all_poses_elite/sacred

### ISSUE THREAD

**Issue by Ealb** [elmokki/nationgen#280]
This cropped up in the most current commit - it's not actually manifesting right now since I implemented a workaround, and I don't have an example seed, but I'm going to make an issue anyway since this is a rather old if rare issue.

Sometimes, races with #all_poses_sacred/elite will throw the error for no such poses being found. I walked through an example of this in debug mode, and the tag literally just wasn't among the race's tags. This used to crop up very rarely with tengu despite their having those tags defined, and in this case with Caelians it only happened occasionally. It isn't a pressing matter since manually adding the tags to individual poses elides the problem, but it's probably worth keeping in mind since something is definitely wrong, even if only rarely, not for obvious reasons, and in an entirely avoidable manner.

**Comment by elmokki** [comment]
As in, you made the program write out race.tags and it wasn't there?

**Comment by elmokki** [comment]
Yeah, so, currently (as in before your workaround) the code for #all_troops_elite/sacred works only for poses tagged as #type "role" and not #type "sacred role" or "elite role". This was probably intentional because it was assumed that if a race has those defined, all troops should not be elite/sacred (and if just "sacred infantry" was defined, all except that are elite).

Now, to get the error no poses have been found if we're talking about the same error. To find poses the program goes through all roles gathered to the list roles, which contains stuff based on race.hasSpecialRole("role"). I don't see a reason it would fail if it receives the role with infantry. race.hasSpecialRole() looks okay as well.

That may be a clue to solving it if it pops again.

**Comment by elmokki** [comment]
I generated a pile of nations where tengus were forced for all elites and sacreds (and each nation had both) without seeing the error. It must be quite rare indeed.

**Comment by Ealb** [comment]
I went into Eclipse debug mode for a seed where the issue was cropping up (because it was only cropping up some of the time, which made no damned sense), and looked at the list of tags present in memory for the race in question. Despite being defined in the race file, #all_poses_elite/sacred were simply not there. The other tags from the race were, but those ones were not. At this point Caelian poses were all just #type "role", but I could unsurprisingly make the problem go away by explicitly defining the tags in each pose, which I did because I was also working through the issue with the armorname field (that took far, far too long for me to figure out, sigh). I'm going to test if eliminating the explicit #type "foo role" tags in the poses makes it crop up again and see if I can find a proper example.

It was really rare, though. I've seen it maybe 5-6 times on tengu in the last year.

**Comment by elmokki** [comment]
There was a sacred generation pose selection change some time early summer too, which may have affected things. 

I think it might be a good idea to write a debug code piece to the db to see how many things are called with wrong column names. I bet there is at least one bug related to that somewhere.

**Comment by Ealb** [comment]
So if I comment out the #type "foo role" in the troops.txt poses file, I immediately get 

Generating nationsWARNING: No sacred (true - actually elite if false) poses were found for Caelian. Consider adding #all_troops_sacred or #all_troops_elite to race file to use normal poses.
Exception in thread "Thread-2" java.lang.NullPointerException
	at nationGen.rostergeneration.UnitGen.generateUnit(UnitGen.java:75)
	at nationGen.rostergeneration.SacredGenerator.getSacredUnit(SacredGenerator.java:613)
	at nationGen.rostergeneration.SacredGenerator.generateUnit(SacredGenerator.java:388)
	at nationGen.rostergeneration.SacredGenerator.generateUnit(SacredGenerator.java:374)
	at nationGen.nation.Nation.generate(Nation.java:291)
	at nationGen.nation.Nation.<init>(Nation.java:104)
	at nationGen.NationGen.generate(NationGen.java:209)
	at nationGen.NationGen.generate(NationGen.java:159)
	at nationGen.GUI.GUI$5.run(GUI.java:420)

on the seed 538614505.

**Comment by Ealb** [comment]
Previously it would sometimes give me 5-6 nations into a batch before that got thrown, but it was the first time this time.

**Comment by Ealb** [comment]
It's really damned weird - the first two nations under -878385423 both have the tag present in the race.tags data structure when I set a breakpoint and check in debug mode, but the third one, where it crashes, is missing those two tags.

**Comment by elmokki** [comment]
I was generating three nations with  -878385423 and third one breaks. Reason is, there are zero roles available to search from. Investigating more.

**Comment by elmokki** [comment]
Yeah. Definitely about missing those two tags.

**Comment by elmokki** [comment]
Addition of race themes removed the tags for some reason

**Comment by elmokki** [comment]
Some very spaghetti-o code in race.addOwnLine is causing this

**Comment by elmokki** [comment]
Yeah. A check for allowing tags to be changed in themes does not take argumentless tags into account.

**Comment by Ealb** [comment]
Okay, then it's fairly safe to say this wasn't the same as the old rare tengu bug, which I don't think I've seen since the summer generation re-writes, FWIW.
