### ISSUE TITLE
Magic/demon/undead mages/priests can't lead their own kind

### ISSUE THREAD

**Issue by Ealb** [elmokki/nationgen#308]
Subject sums it up pretty well. As it stands, basic magic/undead/demon commanders will get undead/magic leadership properly, but casters won't. I took a quick stab at adding it, but failed because mages don't know all their own commands when generated, unlike normal commanders. At that point I realized I wasn't sure where it would be best to add a check to deal with this, and hence the issue.

Ant/fly/spider/scorpion summoners should probably get some magic leadership too - poormagicleader or magiccommand 20, I'd say, though I suppose okmagicleader might be justified. In their case, I'd assume it would be the far-simpler matter of just adding the command into the filter, though...

**Comment by elmokki** [comment]
It would probably make sense to add a pile of code in Unit.polish() that checks if unit is undead/magic/demon and whether it does or does not have related leadership and then if deemed acceptable, adds a suitable amount. 

Like, #noleader means that unless the unit is a mage it probably shouldn't lead anything so demon scouts won't get demon leadership unless specified. Poor leadership results in poor special type, unless mage maybe, and so on.

The alternative is to just handle this at the location mage leadership in general is handled.
