### ISSUE TITLE
SETTING militiaDivider WAS NOT DEFINED!

### ISSUE THREAD

**Issue by ahyangyi** [elmokki/nationgen#314]
Dominions 4 NationGen version 0.6.7 (7th of August 2015)
------------------------------------------------------------------
Loading settings... done!
Loading Edi's Dom4DB... done!
Loading definitions... done!
Generating 8 nations with seed 1066937368.
Generating nations......Nation -1324102275 had a null filter for a mage.
.. Done!
Giving ids........ Done!
Naming things........ Done!
Writing advanced descriptions........ Done!
Writing descriptions........ Done!
Writing items........ Done!
Writing units.CRITICAL FAILURE, IMAGE FILE /graphics/fomorian/weapon/bronzejavelin.png CANNOT BE FOUND.
CRITICAL FAILURE, IMAGE FILE /graphics/fomorian/weapon/bronzejavelin.png CANNOT BE FOUND.
CRITICAL FAILURE, IMAGE FILE /graphics/fomorian/weapon/bronzejavelin.png CANNOT BE FOUND.
CRITICAL FAILURE, IMAGE FILE /graphics/fomorian/weapon/bronzejavelin.png CANNOT BE FOUND.
....... Done!
Writing sites........ Done!
Writing nationsSETTING militiaDivider WAS NOT DEFINED!
SETTING militiaDivider WAS NOT DEFINED!
SETTING militiaDivider WAS NOT DEFINED!
SETTING militiaDivider WAS NOT DEFINED!
SETTING militiaDivider WAS NOT DEFINED!
SETTING militiaDivider WAS NOT DEFINED!
.SETTING militiaDivider WAS NOT DEFINED!
SETTING militiaDivider WAS NOT DEFINED!
SETTING militiaDivider WAS NOT DEFINED!
SETTING militiaDivider WAS NOT DEFINED!
SETTING militiaDivider WAS NOT DEFINED!
SETTING militiaDivider WAS NOT DEFINED!
.SETTING militiaDivider WAS NOT DEFINED!
SETTING militiaDivider WAS NOT DEFINED!
SETTING militiaDivider WAS NOT DEFINED!
SETTING militiaDivider WAS NOT DEFINED!
SETTING militiaDivider WAS NOT DEFINED!
SETTING militiaDivider WAS NOT DEFINED!
.SETTING militiaDivider WAS NOT DEFINED!
SETTING militiaDivider WAS NOT DEFINED!
SETTING militiaDivider WAS NOT DEFINED!
SETTING militiaDivider WAS NOT DEFINED!
SETTING militiaDivider WAS NOT DEFINED!
SETTING militiaDivider WAS NOT DEFINED!
.SETTING militiaDivider WAS NOT DEFINED!
SETTING militiaDivider WAS NOT DEFINED!
SETTING militiaDivider WAS NOT DEFINED!
SETTING militiaDivider WAS NOT DEFINED!
SETTING militiaDivider WAS NOT DEFINED!
SETTING militiaDivider WAS NOT DEFINED!
.SETTING militiaDivider WAS NOT DEFINED!
SETTING militiaDivider WAS NOT DEFINED!
SETTING militiaDivider WAS NOT DEFINED!
SETTING militiaDivider WAS NOT DEFINED!
SETTING militiaDivider WAS NOT DEFINED!
SETTING militiaDivider WAS NOT DEFINED!
.SETTING militiaDivider WAS NOT DEFINED!
SETTING militiaDivider WAS NOT DEFINED!
SETTING militiaDivider WAS NOT DEFINED!
SETTING militiaDivider WAS NOT DEFINED!
SETTING militiaDivider WAS NOT DEFINED!
SETTING militiaDivider WAS NOT DEFINED!
.SETTING militiaDivider WAS NOT DEFINED!
SETTING militiaDivider WAS NOT DEFINED!
SETTING militiaDivider WAS NOT DEFINED!
SETTING militiaDivider WAS NOT DEFINED!
SETTING militiaDivider WAS NOT DEFINED!
SETTING militiaDivider WAS NOT DEFINED!
. Done!
Drawing previews.CRITICAL FAILURE, IMAGE FILE /graphics/fomorian/weapon/bronzejavelin.png CANNOT BE FOUND.
CRITICAL FAILURE, IMAGE FILE /graphics/fomorian/weapon/bronzejavelin.png CANNOT BE FOUND.
....... Done!
Hiding vanilla nations...  Done!
------------------------------------------------------------------
Finished generating 8 nations to file nationgen_sunken_office.dm!

The image not found thing is probably easily fixed (did you forget to add a file?), but the militiaDivider thing has been around for about a week. What caused it?

**Comment by Ealb** [comment]
bronzejavelin.pnc is supposed to be javelin_bronze.png

This is the first time I've seen militiaDivider, though.

**Comment by Ealb** [comment]
I'm not getting it - are you sure you're up to date? Since the current version does indeed have the javelin fixed, it looks like you might not...

**Comment by Ealb** [comment]
Och, no, it's not fixed; there was a second instance of it in the file. Still, I'm not getting militiaDivider errors...

**Comment by ahyangyi** [comment]
I have no idea.

Maybe it's a platform-dependent problem? I'm using Linux.

**Comment by elmokki** [comment]
I removed the militiaDivider setting a while back as it was essentially a duplicate with militiaMultiplier. 

Are you by any chance running the .jar from the repository? If so, it is still 0.6.7 version while settings.txt is not. You can fix this by adding militiaDivider 20.0 to settings.txt I suppose, or the better way to solve it would be by compiling nationgen.jar from source.

**Comment by elmokki** [comment]
That said, the .jar for nationgen should probably not be in repository. Spritegen can stay since it needs updates so rarely.

**Comment by ahyangyi** [comment]
I see. I was running the .jar since I didn't even install javac... That must be the reason.

**Comment by elmokki** [comment]
There's a new .jar in the repository now if you want to play around with it
