### ISSUE TITLE
Nation themes

### ISSUE THREAD

**Issue by elmokki** [elmokki/nationgen#341]
Currently we have racial themes with primary race theme being used as a default if we aren't checking themes for an unit of a secondary race or something similar. I think we should have national themes as well that just affect everything.

The obvious main point behind this thought is the underwater nation theme, which would probably be hardcoded outside normal theme generation. However, I think these should be made generate just like race themes. Mostly these would partially replace nationwidefilters and nationfilters with a bit more convincing stuff: Instead of random stat boosts or penalties and various nation traits why not combine some of them so that colder weather tends to result on cold resistance and so on. This would also allow magic prioritization so that reanimation isn't a small chance upon having death magic but instead getting reanimation (probably) makes nation a death magic nation. It makes controlling probabilities of things a lot easier. 

Actually the ideal situation might be having major and minor versions, so that you might get something more impactful story driven thing like "your guys really like cold weather - you get resistance, preference and your nation spreads cold" and then just random stuff like "nuns occasionally follow priests to battle" (an actual thing that can currently, if extremely rarely, happen to humans and advanced humans by the way)

I also wonder whether the nation's non-bonus mage paths should be generated right after choosing races. Though non-primary race primary mages should be chosen early then as well. In a sense I guess racial distribution could be rolled early, but I see far less benefits in that. Rolling for magic early, on the other hand, allows magic to affect all sorts of theme selection, which is kind of cool. Then again you should be able to just make certain paths really probable already, so I don't know if it matters much.

**Comment by Ealb** [comment]
Aye, right now I've gone the opposite route and had a lot of themes up the probability for given magic paths - this is most dramatic in the cases where theme is acting as subrace or tribal selection.
