### ISSUE TITLE
MageGenerator and dual wielding and two handed weapons

### ISSUE THREAD

**Issue by elmokki** [elmokki/nationgen#38]
Mage generator is just unable to handle Sidhe mages properly. 

They have twohanders in list: Mage generator really does not check whether a weapon is twohander or not so you still get offhands. 
They have long onehanders in list: Mage generator really does not check the length when assigning offhands (which is good since most mage poses have staves etc which are long but which still warrant an offhand)

Solution is that when magegenerator is rewritten poses can be tagged to either use mage or troop algorithm for weapons.

**Comment by Ealb** [comment]
Nice. Otherwise I'd've just suggested the kludge I used elsewhere; i.e., #needs offhand no_offhand plus a null "no_offhand" offhand item.

**Comment by Ealb** [comment]
Hmm, I'm seeing ichtyid sacreds generating with a coral spear in one hand and a coral club in the other, so it looks like the current troopgen isn't checking length either.

Poseium generated with seed -2061517089, with data updated to #60

**Comment by elmokki** [comment]
That's actually a feature for sacreds, but considering how stupid it will look 9 times out of 10, I'll disable it.
