### ISSUE TITLE
chanceInc and mounts

### ISSUE THREAD

**Issue by Ealb** [elmokki/nationgen#40]
In trying to get tribal mounts to crop up as much as I would expect given how much I've progressively increased their chances, I found something that seems odd in UnitGen. I don't feel confident in my grasp of the logic flow to be sure I'm not missing something, but on line 655 in getSuitableItem the final line is:

Item newitem = Entity.getRandom(random, chosen);

I know that weapon selection will take basechance 0 items with a theme tag and add a positive value so e.g. only spider tribe can get poison bows, but their calls are originating in TroopGenerator. Tracing mount selection shows that mounts are being selected w/o applying chanceincs; the base chances from the mounts.txt are the final chances considered, which makes sense given that my generated themed nations seemed to have a random selection of mounts. If I replace that line with:

Item newitem = Entity.getRandom(random, chandler.handleChanceIncs(u, chosen));

I see the distribution of mounts I'd expect (well, almost; I'll get back to that). I haven't seen any other problems, and other chanceincs seem to be firing correctly, so it seems unclear to me why changing this here corrects mounts - I may have missed an earlier invocation for other equipment, though - under the circumstances, I'm fairly sure I did. That, or more than just mounts weren't working - this appears to be the area where mages are getting their themeincs handled. Unless that's the case, regardless of whether this "works", I assume this chanceinc handling should be done somewhere else... but again, my understanding of the precise sequence of execution in NG is not always 100% clear, so I could be wrong on that count too.

The reason I was still getting fewer totem mounts than expected took a bit more digging. With the above change, and ["theme foo +3", "theme totemanimal *0.5", "theme foototem *15"] I was expecting e.g. a basechance 0.5 spider to show up around ((0.5 + 3) * 0.5 * 15) = 26.25 / ~30 (everything else * 0.5 + 26.25 = ~30) around 90% of the time. Too high IMO, but the numbers had crawled up before I found that chanceincs weren't being applied. However, even with those bloated numbers they're actually only showing up around ~2/3s the time: 7.5/11 to be precise. This is actually a pretty good mix, but it shouldn't be happening. I dug into handleThemeIncs, and I found that either my understanding of chanceIncs resolution is very flawed, or there's a problem with the code. My understanding is that the above three chance modifiers should be applied in sequence, so e.g., if there's basechance 0 you'd end up with (0+3) * 0.5 * 15 = 22.5. What's actually happening in handleThemeIncs is (hance = 0 + 3 = 3) (chance = 0 * 0.5 = 0) (chance = 0 * 15 = 0) in sequence = 0. I.e., the basechance is the only chance ever considered so only the final chanceinc in a sequence is applied. Specifically, at line 497 of ChanceIncHandler's handleThemeIncs (and presumably again at 509)

filters.put(f, applyModifier(f.basechance, args.get(args.size() - 1)));

sets filters(f).basechance = f.basechance * modifier for each modifier in turn, rather than doing filters(f).basechance = filters(f).basechance * modifier for each modifier in turn, where filters(f) starts off as f,basechance. My first thought was that the filters.put(f, foo) might be setting f.basechance to foo (i.e., that f was a pointer to the object residing in the hashmap filters at the location hashed to by f), but stepping through in Eclipse makes it clear that f and the object at filters(f) are distinct objects. This seems to be a pervasive problem with chanceincs, based on my understanding that they resolved in sequence, not merely taking the last one and ignoring the rest. I hadn't ever previously really traced into the code to confirm that anywhere, but I've been writing data files according to the assumption I can create sequences for a year now, so unless this just changed (and it doesn't seem to have?) there's a lot of wonky chances that aren't improving/decreasing like they're supposed to...

(I had ,07E sitting on my machine, and it has the same filters.put(f, appMod(f,basechance, foo)) structure in handleNationIncs, so it looks like this error has been with us for a while, assuming I'm correct in thinking it's an error.)

**Comment by elmokki** [comment]
As for the mounts, it's probably just a place where mage and troop generation share code. As I said a while ago, chanceinchandler was written for filters originally so the equipment don't always have chanceincs handled. This is one of the reasons rewrite is needed.

As for chanceincs, yes, I would consider it a bug as well. It may have been WAD at some point ages ago, but what you described was exactly how I thought it worked. I would guess that the way there was sufficient originally ages ago and when additional functionality and more complex chanceincs were added. I'll fix this one - it's a job of writing a small method and copy-replacing hell of a lot of stuff. Extremely nice find and the kind of bug I hope is very rare since spotting these is very hard.

**Comment by elmokki** [comment]
I won't fix the mount thing - feel free to do it yourself - since I kinda just want to rewrite the code anyway. Also, I'm gonna add a .getRandom() to chanceinchandler so you don't have to nest a chanceinchandler call inside getRandom() every time pretty much everywhere.
