### ISSUE TITLE
#price_per_hp and similar commands

### ISSUE THREAD

**Issue by elmokki** [elmokki/nationgen#402]
I have been planning to do some stuff related to naming and maybe finish the PD generator update at some point (EDIT: Also those nation themes since they'd really help with consistency and allow adding some funkier stuff more reliably), but reading some forums this came to mind. I might even make it a generic `#price_per_command <command> <price>`, but mostly hp scales so well with stuff like regen, glamour etc that those probably need nerfs.

**Comment by Ealb** [comment]
More tools to allow finer-tuned balancing would be nice, yes. Although that of course requires that they get implemented, which *I* certainly am not the best about...
