### ISSUE TITLE
Update data files with new/revised bronze/bone/stone weapons

### ISSUE THREAD

**Issue by Ealb** [elmokki/nationgen#413]
4.23 added a number of new items, so this is a reminder to go through the files and replace any obsoleted customitems, or just plain add new stuff as appropriate (e.g., bronze axes).

**Comment by elmokki** [comment]
The item database needs to be updated. Dom4inspector seems to have the updated data already and nationgen.unrelated still has my database conversion code so it should be fairly easy. I can do it later today.

**Comment by Ealb** [comment]
In terms of UW support and rusting, all custom items which rust currently have either #ironweapon or #ironarmor, accordingly. All non-rusting items (bronze, leather, meteorite iron, etc.) lack said tag.

**Comment by elmokki** [comment]
Great work, though I think the database has the ferrous tag as well?

**Comment by Ealb** [comment]
Bah, you're right that #ironarmor isn't a real tag. I'm not sure there's actually a way to set ferrous for armors with mod commands right now; the modding manual certainly doesn't show anything, unlike for weapons.

FWIW, all custom armor that should be iron has the useless "#command '#ironarmor'" tag right now.

**Comment by elmokki** [comment]
I wonder whether `#ironweapon` would work on armor too. It could.

**Comment by Ealb** [comment]
That actually sounded like a pretty reasonable theory, but testing shows it doesn't.

**Comment by elmokki** [comment]
Oh well, the tags can be used to not generate iron armor underwater even if it's mostly thematical, though technically it's the item definitions and not custom item definitions that have to be tagged.
