### ISSUE TITLE
Too many foulspawns

### ISSUE THREAD

**Issue by ahyangyi** [elmokki/nationgen#456]
I guess you are testing foulspawns but somehow committed the changed weight for testing into the master branch. I just did a git pull, and generated a mod with 8 races. All of them have foulspawns...

**Comment by elmokki** [comment]
Yeah, we do stupid crap like that, partially because we don't expect anyone to actually pull the repository. If you want to get rid of the flood of foul spawn, edit /data/races/foulspawn.txt `#basechance 10000` to `#basechance 0`

**Comment by Ealb** [comment]
Yeah, sorry about that. Foulspawn.txt in the races directory is at
basechance 10000. It is indeed a testing state, and I'll make sure to fix
it the next time I'm on my dev machine.

**Comment by ahyangyi** [comment]
Thanks. I should have fixed it myself. I thought it would involve changing multiple locations due to foulspawn having many flavors.

**Comment by Ealb** [comment]
If you ever pull a build and see nothing but one race showing up, all you'll probably ever need to do is go into races, find that race, and get rid of a line that someone - probably me - left in setting the basechance to 10000 or so.
