### ISSUE TITLE
No racial themes in current version?

### ISSUE THREAD

**Issue by ahyangyi** [elmokki/nationgen#459]
Hi,

Sorry for bringing another issue, but apparently all generated nations have races without themes, at least according to the generated advanceddescriptions.txt file.

**Comment by elmokki** [comment]
Don't be sorry!

Are you perhaps running it from the .jar? I had to change the naming of racial themes as they were named nationthemes internally and I was adding actual nation themes separately, which may cause some issues if the old codebase is used. Running it from Eclipse results in for example:

> National traits:
> - Ideal cold level -1
> - Can build forts underwater
> - default
> 
> Muuch themes: green, advanced, slaver
> Caveman themes: default, slaver

The .jar is updated only when we release. I suppose we should have a separate release branch where that is kept to keep it separate or something, but oh well. It does really show.

I can compile a new .jar for the depository if you need it. Just tell if you want it.

**Comment by ahyangyi** [comment]
I see. I'll just recompile it myself. Thanks!
