### ISSUE TITLE
Official Thread

### ISSUE THREAD

**Issue by TomClancyIsDead** [elmokki/nationgen#461]
Now that Desura seems to have fully kicked the bucket, where will the official thread for nationgen live?

**Comment by Ealb** [comment]
When Desura first started its shambling undeath, the plan had been Dom4Mods (http://z7.invisionfree.com/Dom3mods/index.php?showtopic=1619). As neither I nor Elmokki have ever expressed any particular fondness for the Steam forums, I'd assume that's still the case. Although I suppose we'll have to make a point of announcing updates in the Steam thread (http://steamcommunity.com/app/259060/discussions/2/648816743164577764/) as a matter of courtesy/convenience.

**Comment by elmokki** [comment]
Yeah, that's probably the best idea.
