### ISSUE TITLE
Multiple property dom4 mod inspector

### ISSUE THREAD

**Issue by TomClancyIsDead** [elmokki/nationgen#483]
Hey, I added multiple property search to the mod inspector. Not posting elsewhere outside of SA so Larz has time to pull it in to the main, but figured it's a tool that might help you two. http://tomclancyisdead.github.io/dom4inspector/

**Comment by Ealb** [comment]
Oh geez, that's lovely. I'd been lamenting the lack of multi-property search on the inspector maybe an hour ago...

**Comment by TomClancyIsDead** [comment]
Glad I could help. It's been bugging me since I first started playing dom.

**Comment by Ealb** [comment]
(Closing this since Larz pulled it to the main branch)
