### ISSUE TITLE
Survivals for scouts

### ISSUE THREAD

**Issue by Ealb** [elmokki/nationgen#513]
Looking at Ysian Scouts in 4.25 made me think of a small Quality of Life issue that I'd considered before: most scouts should probably have some survival or another (with standards being forest+mountain; every vanilla national scout that's not amphibious, mounted, or flying has both of these), whereas right now almost all have none unless the base national troop has some.

This is pretty minor since scouts who are sneaking in hostile territory will be moving one per turn anyway, but it will help make them if not actually attractive at least not *less* attractive than indy scouts in terms of raw stats.

I assume this would be best handled as a template rather than something internal to the engine?

**Comment by elmokki** [comment]
I'd just slap it into scoutgenerator unless you have something probability-based in mind. I mean, theoretically of course we could have two survivals based on magic paths and stuff like that.
