### ISSUE TITLE
Minotaur two handed leather cuirass missing

### ISSUE THREAD

**Issue by elmokki** [elmokki/nationgen#56]
CRITICAL FAILURE, IMAGE FILE /graphics/gaian/minotaur/armor/2h/leathercuirass.png CANNOT BE FOUND.
CRITICAL FAILURE, IMAGE FILE /graphics/gaian/minotaur/armor/2h/leathercuirass.png CANNOT BE FOUND.
CRITICAL FAILURE, IMAGE FILE /graphics/gaian/minotaur/armor/2h/leathercuirass.png CANNOT BE FOUND.
CRITICAL FAILURE, IMAGE FILE /graphics/gaian/minotaur/armor/2h/leathercuirass.png CANNOT BE FOUND.

No such graphic exists.

**Comment by Ealb** [comment]
...I'm kinda impressed that got through testing, though I suppose it comes down to randomness vs. minotaurs' least common pose.
