### ISSUE TITLE
Foulspawn priests are recruiting templates as units

### ISSUE THREAD

**Issue by Ealb** [elmokki/nationgen#566]
Example: Pi-rameer generated with seed -269631855

![preview_106_pi-rameer](https://cloud.githubusercontent.com/assets/12613576/16542057/6ce984aa-4066-11e6-8ede-f516b57da551.png)

-- Priests:
** Neophyte Exarch (Foulspawn), 50g, 1r, Touch of Leprosy, Pincer, Robes.
--- 1H.
--- Sacred, inquisitor and elegist 1
** Adept Exarch (Foulspawn), 85g, 3r, Trident, Robes.
--- 2H.
--- Sacred
** Greater Exarch (Foulspawn), 155g, 1r.
--- 3H.
--- Sacred
-- Mages:
[...]
** Olive Father (Foulspawn), 225g, 1r.
--- 1S 3N 1.1? (blood, nature, death, astral).
--- Capital only, Slow to recruit and Becomes unit of montag 1000 when recruited

Both the T3 mage and priest show up as "Primary Mage" template units in the recruitment screen, but unlike Olive Fathers, Greater Exarchs remain the template unit after recruitment (which is in keeping with the Advanced Description's lack of a "Becomes..." line for them).

**Comment by elmokki** [comment]
Mage and priest main pose needs to be split. The only available tier 3 mage/priest pose is the category pose and it's good for mages but not for priests. Could you do it?

**Comment by Ealb** [comment]
Yeah, that shouldn't be a problem.
