### ISSUE TITLE
Balance Notes

### ISSUE THREAD

**Issue by TomClancyIsDead** [elmokki/nationgen#603]
- 1x1x1x1x2y ?x mages are a bit too cheap.
- Crocodile Riders are awful - they are slow, bigger, don't get extra attacks compared to the sobeks riding them, expensive for low prot and no defense. 
- More to come.

**Comment by elmokki** [comment]
I addressed the first one to a degree already

**Comment by Ealb** [comment]
...could give them sailing with only enough capacity to carry the unit. That way if you had a sailing commander (like e.g. a croc rider commander) they could sail with all the croc rider troops coming along for free. It's what I did with swan riders and swan chariots.

**Comment by TomClancyIsDead** [comment]
That + the tail attack might be enough that they are worth recruiting sometime.

**Comment by elmokki** [comment]
Would that actually work? I thought sailing on units does not work at all.

**Comment by TomClancyIsDead** [comment]
Yeah I believe units with sailing don't take up sailing space. It's a trick used in Ys for their sacred cav.

**Comment by elmokki** [comment]
That'd be a neat solution indeed

**Comment by Ealb** [comment]
FWIW, I'm setting up an all-Foulspawn MP game on my native forum, so I should soon have some strong opinions about how (un)balanced those are.
