### ISSUE TITLE
Dustwalker secondshapes

### ISSUE THREAD

**Issue by elmokki** [elmokki/nationgen#676]
Living secondshapes for undead feel weird to me. I think I may disable all secondshapes from them or alternatively I'll disable them and look at what sort of undead animals there are sprites for.

It'd be hilarious to have undead were-undead-bears.

**Comment by Ealb** [comment]
There's some bearish/big-cattish skeletons, yeah. Vine ones too, even if that seems a bit odd for burning desert dwellers.

I think in general there's a fair number of the shapechanges that would make sense to restrict from undead in general. If I ever get around to adding in ghouls to any nation (following the LA Ulm precedent of ghouls-for-gold rather than strictly summoned/raised ghouls), it would probably be reasonable to expect them to not turn into living beings either (although yes, it'd feel far less weird with ghouls than with something skeletal...)

**Comment by elmokki** [comment]
What do you think about living -> undead shapes?

I think they're fine. Currently both ghoul and ghost won't let the unit turn back which is better, but I could live with a living being who loses his life briefly and then gains it back.

**Comment by Ealb** [comment]
It would be weird. I could see it being fine as a general principle, but I can't actually think of a specific example that makes sense. Maybe ghouls, though even that seems odd. Well, actually... there's the oni model of lingering as a spirit until the body reforms/heals. Something like that could seem coherent. 

To take another tact, having a unit's shadow (shade) avenge its death would probably be a reasonable filter to have. It's a pity units can't have battle summons, or I'd say it might be interesting to have a unit which detaches its shadow to fight with it (though yes, that'd probably be *really* hard to balance). Commanders could have that, though... give the filter a command to make the shadow slot not generate and give them a battle summon blackscale version of themself...

**Comment by elmokki** [comment]
Current ghost shape should be a greyscale of original sprite
23.7.2016 2.27 ip. Ealb <notifications@github.com> kirjoitti:It would be weird. I could see it being fine as a general principle, but I can't actually think of a specific example that makes sense. Maybe ghouls, though even that seems odd. Well, actually... there's the oni model of lingering as a spirit until the body reforms/heals. Something like that could seem coherent. 

To take another tact, having a unit's shadow (shade) avenge its death would probably be a reasonable filter to have. It's a pity units can't have battle summons, or I'd say it might be interesting to have a unit which detaches its shadow to fight with it (though yes, that'd probably be really hard to balance). Commanders could have that, though... give the filter a command to make the shadow slot not generate and give them a battle summon blackscale version of themself...
