### ISSUE TITLE
Serpentmen

### ISSUE THREAD

**Issue by elmokki** [elmokki/nationgen#680]
I got this message:

Hello again.
I'm the guy who submitted the carpmen for nationgen.

Not long ago I started a more complex project - adding a serpentman race with sprites based on the hydra hatchling. After correcting lots of equipment (mostly adapted atlantian and some human gear), armor, a single mage cloak, headgear sprites, I started making the data files.

The only things are missing from making it all work are the weapons definition file, and the theme file. Themes and poses really confuse me, especially since I wanted to add two subraces.

But anyway, I'll submit my WIP things that I probably won't work again on now. Maybe you'll like the sprites or the concept and decide to add it, or to discard it. I won't mind either way. I hope you'll make a better use of my efforts than I did.

I uploaded them here:
http://koti.kapsi.fi/~elmokki/dom4/unitgen/serpentmen.rar

They look like a pretty good rarer race to spice things up, but I'm not very motivated to do anything for them right now. Feel free to do something if you feel like it. If not, I may or may not do it later.

**Comment by Ealb** [comment]
I'll look at it. I haven't been terribly motivated myself the last few weeks, but inspiration may strike.

**Comment by Ealb** [comment]
Hmm. Those are kinda cute. Although that one stray icecap immediately made me think of adding two more demographics (fire and frost). I may screw around with this tonight after all...
