### ISSUE TITLE
A New Race request in the next patch

### ISSUE THREAD

**Issue by Kungfuwonder** [elmokki/nationgen#686]
I am A Fan of your mod for awhile and i wanted to know if you can create a new Race to generate some thing with 4 arms maybe. And 2 heads i know that you are doing a lot of stuff but can you make some spare time and do this to

**Comment by elmokki** [comment]
Some kind of shivans would be cool as long as they're large (size 3 or 4) so the potential 4+ attacks per unit won't be too stackable. I suppose the Bandar Log summons have potential for spriting. Chances are neither one of us will bother but who knows. Someone else (like you) could do the sprites and definitions though!

That said, this isn't really a place for suggestions or feature requests, so I'm gonna close this.
