### ISSUE TITLE
Content requirements for 0.6.21

### ISSUE THREAD

**Issue by Ealb** [elmokki/nationgen#708]
All of these are fairly far along, and will make a decent (content) core for a 0.X.x version release. More or less by happenstance and whim, it looks like it'll largely be an Indian-themed patch. Well, or else a snakemen-themed patch. Well, both, really.
- ~~Finish serpentmen~~
- Finish "Enlightened humans"
- Finish naga
- Finish occidental humans

The following are some additional WIP things I could probably finish in a modest amount of time, if I can stay focused/motivated/free of random setbacks. They'll be viewed as optional, depending on how fast/slow all the core stuff goes:
- Add Yakshini
- Add certain celestial beings as recruitable potential mage chassis
- Look into how hard it would be to do dynamically-defined shapechangers (i.e., greater naga mages with Yakasha/Yakshini forms)
- Finish Ettinlings as another ogre demographic theme
- Finish Enkidu
- Look into finishing any of the other myriad bits and pieces I've started but not finished: big Atlantian/muuch mages, ~~primate colossi,~~ vine hoburgs, imperial humans, etc. etc. etc.

**Comment by elmokki** [comment]
> Look into how hard it would be to do dynamically-defined shapechangers (i.e., greater naga mages with Yakasha/Yakshini forms)

I will eventually make terrain shapes once I will eventually make UW support and that probably can also handle innate shapeshifting (and more importantly, shapeshifting with gear carrying over somewhat). When that is, I cannot say.

**Comment by Ealb** [comment]
Honestly, given which/how many nagas can shapechange, I'm not overly concerned about this - it feels like a national quirk of Patala's rather than a fundamental characteristic of nagas, although I don't doubt that many people will perceive it as such.

**Comment by Ealb** [comment]
...obviously the requirements have gone off the rails since my complete and utter occidental sidetrack started. If I get a bit more focused motivation, I'll try to revise what's a reasonable patch scope that's within my near-term motivation's limits.

**Comment by Ealb** [comment]
This is archaic, even if I'll still get the unfinished parts done eventually, so I'm closing it.
