### ISSUE TITLE
Themeincs in themes

### ISSUE THREAD

**Issue by Ealb** [elmokki/nationgen#72]
Themeincs (probably) do not affect other themes in the same race.

Not a huge issue from where I stand as I am indeed using "#chanceinc racetheme foo *X" to make a particular theme more likely if a previously-defined theme exists. I also can't immediately think of any situation when I'd need themeincs in a theme, but I know you've had some different usage ideas than I have in re: themes. I will need to verify the freethemes are added in sequential order so e.g. there will be a techlevel theme already in place when a regional one is picked, but I'm pretty sure that's so.

Hmm. Although. If `"#chanceinc racetheme <theme> <mod>"` does not, as the documentation states, support `"#chanceinc [not] racetheme <theme> <mod>"` I could definitely see value in adding negation support, although this usually can be worked around.

**Comment by elmokki** [comment]
Freethemes should be applied in sequence. Racetheme chanceinc does indeed not support negation, but I need to note that the sequence is always #chanceinc whatever [not] <whatever parameters> <modifier>. 

How I have been writing chanceincs like this is to take the two last arguments as the modifier and as the parameter and then just checking if anything between the chanceinc keyword and the two last arguments was not, so basically boolean not = args.contains("not"); and then instead if if(ok) the check is if(ok != not) in which case it will pass only if not was not found and it was ok or vice versa. Very minor if you wish to do it.

**Comment by Ealb** [comment]
I'll try to wade in and implement this tonight. I may also try to add something more cumbersome like "chancein racethemetype <type> [not] <theme>" to allow for checks like e.g. if there's a "regional" theme that's not "oriental". Honestly, [not] in that probably shouldn't be optional as without negation it'd be the same as "racetheme", so I could even go for a really cumbersome keyword like "racethemetypenot", but sticking to the standard syntax even if it always has to have "not" would probably be clearer.
