### ISSUE TITLE
Lizards never wear pants?

### ISSUE THREAD

**Issue by Moggers** [elmokki/nationgen#728]
I've never had nationgen give me a lizard nation where any of the lizards wear pants.

**Comment by elmokki** [comment]
They don't like pants.

**Comment by Moggers** [comment]
Wow didn't expect a response within thirty seconds.
Am I just really (un)lucky and getting all the exhibitionist lizards?
I know spritegen can spit out lizard sprites with pants.

**Comment by elmokki** [comment]
Oh yeah, you mean leg armor. They should get it for full chain/plate/scale at least and I saw nothing wrong in the code.

**Comment by Moggers** [comment]
Yeah, I see. I got a lizard with mail and he was wearing a cute little mail skirt.
