### ISSUE TITLE
Unable to get Nationgen to work.

### ISSUE THREAD

**Issue by FleetingFrost** [elmokki/nationgen#744]
I have extracted the WinRAR and it looked like this. https://gyazo.com/8b0d695fb8031c8b4fd2d5343cec46d4 I was unable to open it unless I open the .jar with java. But after that I was unable to get it to work as before I started it said this

 "SETTING advancedDescs WAS NOT DEFINED!
SETTING basicDescs WAS NOT DEFINED!" 

After starting it, I received errors saying: "Loading settings... java.io.FileNotFoundException: C:\WINDOWS\system32\settings.txt (The system cannot find the file specified)"
"Error loading file C:\WINDOWS\system32\units.csv (The system cannot find the file specified)
java.io.FileNotFoundException: C:\WINDOWS\system32\forbidden_ids.txt (The system cannot find the file specified)"

How can I get my nationgen to work?

Thanks for any help.

**Comment by elmokki** [comment]
Same error was reported on Steam forums a while back.

Basically the program thinks, for some reason, that it is in C:\Windows\system32. Java reinstallation might fix it in general, but at least on Windows there's a fairly easy alternative that might work:

1. Create a shortcut of nationgen.jar
2. Right click shortcut and select properties
3. Change "Start in:" to whatever directory NationGen is in (unless it's the default in which case just try the shortcut)

I'm not sure this works for you but I can reproduce your error by changing start in to C:\Windows\System32 so maybe the inverse works as well.

**Comment by FleetingFrost** [comment]
I created the shortcut but in 'start in' it was default of the directory to what nationgen is in. Using the shortcut version didn't make a difference its still saying the same errors.

Also tried reinstalling java but it didn't work ;/.

Thanks for the help.

**Comment by elmokki** [comment]
I will, at some point, change the directory determination and that may or may not help.

**Comment by elmokki** [comment]
...also, you may wanna try running it as administrator. Who knows if it is somehow related to that.

**Comment by FleetingFrost** [comment]
I can't run it as admin because of winrar, have to open it up with java.

**Comment by ahyangyi** [comment]
@FleetingFrost Google "change file associations on windows <your windows version here>" and use the guides you found to change file associations for `.jar` files to use Java Runtime.

**Comment by FleetingFrost** [comment]
Wow thanks this worked. ^^
