### ISSUE TITLE
New sacred generation

### ISSUE THREAD

**Issue by elmokki** [elmokki/nationgen#761]
This is entirely an idea because I haven't exactly done a lot lately, but better write it down:

Currently sacreds are generated by just generating units and adding some features to them. I think sacreds should get any features they're getting first and figure out stats and gear afterwards. This gives ability to tie some filters better to sacreds and probably to also limit their interactions more easily.

Like, instead of making awe more likely on light armor, make awe make heavy armor more likely. I also want sacreds that are kinda like flagellants: Cheap, recruit everywhere and not too spectacular.

**Comment by Ealb** [comment]
Tied to that, a national tag and/or filter for more sacred varieties in a given nation would be good (with presumably most or all of them being cap-only). That was one of the distinguishing characteristics I wanted to tie to occidental cultures to balance out their more primitive gear. It'd also let me be a lot more aggressive in tying certain shapechanges to certain outfits.

One thought is that it would probably still be good to get the very most basic of stats first so filters could check against size, etc. Currently, that's in race sometimes, pose sometimes, and basesprite just as often. Um, and sometimes in wings. If there was a #statsin <slot> tag or somesuch (presumably where more than one was allowed) to make sure the necessary slots for informed filter selection got picked before sacred filters, I'd be more than willing to dig through the mess of existing nations and make sure all elite-/sacred-eligible indicated where/if they're hiding their base stats.

**Comment by elmokki** [comment]
Sacred varieties and such being not hard coded should be trivial. I kind of want to make a system where there's a chance that 2+ sacreds tend to sometimes be varieties of each other like Jomon sacreds. Something like very similar gear and different special abilities.

It'll work like the troop templates (ie elite +1 or forestsurvival or whatnot for basic roster): First generate a naked unit, then generate the filter(s), then generate gear. Sacreds would get extra stats to the equation too and their gear generation includes magic weapons. This way all the current chanceincs that are based on innate race/pose/basesprite based unit commands and #generateitem items still work. #statsin or similar would not work as the program cannot know what will be generated, but I think #generateitem can handle wings and such anyway, right? 

The issue with current system is that it's very random. I mean, sure, the program is random too, but it's uncontrollably random: It just makes an unit and then randomly adds stats/filters/magic stuff on it until it feels like it's done. Having it more structured allows code to make some very cheap massable sacreds and it also potentially allows way more thematic sacreds as it's a lot easier to, for example, make a wolf shapeshift heavily increase the odds of wolf-themed gear.

**Comment by Ealb** [comment]
If the "naked unit" includes #needs within the used slots, it should be fine. There are some units where that would matter; e.g., flying monkeys which get their wings from their baseslot.

For the most part, I wanna say I don't have any (or at least not many) #generateitem tags that are gear rather than more intrinsic stuff like hair or scales or wings. I'm sure there's some, but it'd still be more structured than the current system.

**Comment by elmokki** [comment]
As far as I remember, it includes basesprite, shadow, hands, maybe pants, #generateitem items and any #needs of those.

Basically if units work currently fine as troops they should work fine as sacreds. Though whether something works precisely as intended may be hard to know.
