### ISSUE TITLE
Black steel infantry #needs bug

### ISSUE THREAD

**Issue by elmokki** [elmokki/nationgen#779]
!!! full plate on slot armor tried to link to platepants on list legs, but such item was not found. Check your definitions! Pose [infantry, elite infantry, sacred infantry], race Boreal human
!!! full plate on slot armor tried to link to full on list hands, but such item was not found. Check your definitions! Pose [infantry, elite infantry, sacred infantry], race Boreal human
!!! full plate on slot armor tried to link to platepants on list legs, but such item was not found. Check your definitions! Pose [infantry, elite infantry, sacred infantry], race Boreal human
!!! full plate on slot armor tried to link to full on list hands, but such item was not found. Check your definitions! Pose [infantry, elite infantry, sacred infantry], race Boreal human
!!! full plate on slot armor tried to link to platepants on list legs, but such item was not found. Check your definitions! Pose [infantry, elite infantry, sacred infantry], race Boreal human
!!! full plate on slot armor tried to link to full on list hands, but such item was not found. Check your definitions! Pose [infantry, elite infantry, sacred infantry], race Boreal human
!!! full plate on slot armor tried to link to platepants on list legs, but such item was not found. Check your definitions! Pose [infantry, elite infantry, sacred infantry], race Boreal human
!!! full plate on slot armor tried to link to full on list hands, but such item was not found. Check your definitions! Pose [infantry, elite infantry, sacred infantry], race Boreal human
!!! full plate on slot armor tried to link to platepants on list legs, but such item was not found. Check your definitions! Pose [infantry, elite infantry, sacred infantry], race Boreal human
!!! full plate on slot armor tried to link to full on list hands, but such item was not found. Check your definitions! Pose [infantry, elite infantry, sacred infantry], race Boreal human

This is probably black steel. Error message is stupid and doesn't even try to tell pose name, but I think the only poses with those are the black steel ones.

**Comment by Ealb** [comment]
That's really weird. The definitions look right. Hmph, I'll dig deeper.

**Comment by elmokki** [comment]
It was something strange and now that I checked it, don't bother. The things actually work in SpriteGen so they probably work on live and this was probably something really strange. If it ever pops up again then it needs to be looked at.

**Comment by Ealb** [comment]
Already found it, and am committing a fix. Blacksteel ghoul plate hauberks and full plate had dependencies like normal human armor instead of like advanced human armor, even though their armor acts like advanced human armor. Cut-and-paste error, d'oh.
