### ISSUE TITLE
Enchanted sleep touch

### ISSUE THREAD

**Issue by Lambert-Simnel** [elmokki/nationgen#786]
Nation seed -1248440397
The enchanted sleep touch weapon it creates as a scared foulspawn weapon is as follows, which does not do stun damage but rather 30 magic damage with no mr negation.
#newweapon 704
#name "Enchanted Sleep Touch"
#rcost 0
#att 2
#def 0
#len 0
#dmg 30
#magic 
#nostr 
#range 0
#ammo 0
#end

**Comment by elmokki** [comment]
Yeah. The magic weapon system isn't apparently built to handle anything too special. It should be an easy fix. Thanks for reporting the bug.
