### ISSUE TITLE
0.6.21c or 0.6.22

### ISSUE THREAD

**Issue by elmokki** [elmokki/nationgen#798]
...should happen soonish consider how many bugs there are. Feel free when you are ready.

**Comment by Ealb** [comment]
If I can stop adding and tweaking crap, I could probably finish knocking out Nephil hero poses for Avvite nations in an hour or two and say content it's content enough for 0.6.22 (even if it's really not much at all, though it does point to how readily we could do some more ridiculous hero-only junk)
