### ISSUE TITLE
Query about rigid roster definition

### ISSUE THREAD

**Issue by Ealb** [elmokki/nationgen#814]
It occurred to me that if I ever make Imperial humans, it would probably make sense for them to have as one of their distinguishing characteristics besides gladiators a roster that to a certain degree is fairly inflexible. I.e., a randomly generated legion structure, but a legion structure none-the-less. I think I can see how to do that now with a tightly defined number of national troops plus a bunch of different poses defining the various battle lines / classes of infantry, each with a strict #maxunits 1 #maxvariants 1 and very heavy weights to assure that all classes of legionary troops are represented before miscellaneous troops like gladiators or such get added. However, having just looked at how messy my old clockwork data definitions were, it occurs to me that it might be better for me to bounce this off of you before I try to force the engine to do something it's not strictly intended to.

Would the engine be able to deal with a pose set that tried to force it to define a fairly fixed structure for most of the roster as roughly described above, or would it be better to add some national commands like e.g. #needspose foo X (foo = pose, X = how many units of those) to explicitly guide it along?

**Comment by elmokki** [comment]
#needspose makes sense if you want to have at least X units of certain pose but want to have an option of having more than X of those. It shouldn't be horribly hard to add either as it's basically going to be a check at the code that chooses new poses to only choose #needspose poses until they've been fulfilled.

It can also be made to work with #type or something so you can just force x legionnaires or something.

If you want just a single legionary of each type then the #maxunits #maxvariants route is entirely sensible too.

**Comment by elmokki** [comment]
Actually, scrap that, the way it currently works probably doesn't consider pose chances for making units itself but for choosing a pose to potentially make units with. That should maybe change.

**Comment by Ealb** [comment]
Good point about type. If #needspose gets added, it would be handy to have #needsposetype as well.

**Comment by Ealb** [comment]
I'm reasonably happy about how I can abuse the system to get approximately the functionality for Imperial legions I was discussing here, so I'll close this.
