### ISSUE TITLE
More flexible nation filtering and possible bug

### ISSUE THREAD

**Issue by elmokki** [elmokki/nationgen#816]
First: 

#815 just puts a bunch of if statements after certain generation steps. I think it'd be better to add some sort of step identifier to the filters like "sacred" or just an arbitrary number and then run some generic checkRestrictions("sacred") after sacreds have been generated. Integer is more efficient but needs documentation or to be looked from code, which isn't really an issue though.

Secondly:

I don't think the code in #815 actually works as it is supposed to if you have multiple restrictions of the same type. That's not good. You may want multiples since a restriction for fire and air magic is fine with either one but one restriction for each requires both. 

So:

Just make checkRestrictions that loops through restrictions and checks all the ones that have matching step identifier to the argument passed to the method. This is less efficient in the sense that you'll have to for loop in every step, but then again I'm pretty sure looping through even something like 50 restrictions is negligible in terms of CPU usage. The upsides are that firstly it allows for multiple filters of same type and secondly it requires zero changes to Nation.java if you want to add new filters.

**Comment by elmokki** [comment]
I can do this too but I'll leave this open for now if Freykin wants to change it himself or to argue for a different solution to at least the second point.

**Comment by Freykin** [comment]
Ah, I don't think I tested it with multiples of the same restriction type; it didn't even occur to me that you could do that. It definitely needs to be changed then; keeping it as all if statements is kind of silly too. It'd probably make the most sense to be a function that's called after each step with the type of restriction to check for, that then does the right thing based on what type is passed in. I'll focus on that on Saturday.

**Comment by Freykin** [comment]
I've got the restriction filtering all fixed up on my end; it now calls a function several times to check against restriction types as it goes, with support  for multiple instances of the same restriction. Ran a test last night with all filters active and several instances of magic access restriction, and it handled it all properly.

Should I keep working on a fork of the main project, or create my own branch on here? I know at the moment I do not have access to do the latter.

**Comment by elmokki** [comment]
You should have a collaborator invite now. Whether you work locally or branch here doesn't matter.

If you do some major changes, as you're bound to do if you keep doing what you are doing, be careful with merges. Though we can always revert so it's not a huge issue if something breaks.

**Comment by Freykin** [comment]
I've created a branch on here that's separate, and I'll continue doing pull requests so any major changes I make get looked over first.

**Comment by Freykin** [comment]
And I apparently failed at doing that right, as it committed to a new branch and master at the same time. Doing pull requests is new to me; I work at a tiny company where there's only two coders, so we just deal with merging conflicts as they arise, which is rare. Guessing I needed to make the branch before making any changes and not after.

**Comment by elmokki** [comment]
Seems fine though. I would've added a new identifier attribute to the restriction base class and used that so there's no need to tweak the code in Nation.java at all if you add new things, but it's not like nation filters are added in such large quantities that there's too much point in that.

And yeah, you branch first and commit to branch and then pull the branch to the main.

**Comment by Freykin** [comment]
By Identifier attribute, do you mean a string that contains the restrictions name, or something more specific? We use Identifiers from a code library in C++ at work, but I'm not sure they're the same in Java as they are there.

**Comment by elmokki** [comment]
I just mean something like String identifier = "RUN THIS AFTER SACREDS ARE GENERATED" (could be an integer or whatever). Then instead of manually putting suitable filters to the list for each step you pass the identifier to the method and have the method collect all suitable filters. Inefficient but negligibly so in this context.

But like I said, it doesn't really matter. If it was something that will be built on a lot then flexibility would be nice. However, chances are nation filters aren't something someone will make tons of or build a new system on top of or something. Adding a small bit of code to Nation.java for each filter added shouldn't be big issue.

**Comment by Freykin** [comment]
Okay, wanted to make sure I had terminology right; I know a lot of the code library I use at work is to bring some java like functionality to C++, so I wouldn't have been surprised if Identifier was a Java specific thing.

**Comment by elmokki** [comment]
It could be! I'm a terrible source for java terminology or coding practices.

**Comment by Freykin** [comment]
I couldn't find anything specific besides that variable names are referred to as identifiers, so thought i might have been missing something :)

**Comment by Ealb** [comment]
...I would love to helpfully weigh in on Java terminology and coding
practices, and if it were 2007 I probably still could. Alas, alas...
