### ISSUE TITLE
Cavalry/chariots have boot slots

### ISSUE THREAD

**Issue by Ealb** [elmokki/nationgen#819]
I'm going to assume that adding #itemslot foot -1 to all mounted/chariot poses would be the fastest and easiest way to correct this, but I'm asking just to make sure I'm not missing something better.

**Comment by elmokki** [comment]
The easier alternative is to add this to all mounted units by adding it to where-ever other mounted related stuff in Unit.java happens. This is of course less flexible in case mount slot is some day used for something more innovative, but then again in such case the other mount exceptions probably need a rework too.

**Comment by Ealb** [comment]
I'll go with the more flexible/less robust solution for now...
