### ISSUE TITLE
Extra quotes in description string

### ISSUE THREAD

**Issue by Aciho** [elmokki/nationgen#829]
https://snek.earth/stuff/nemorousgate.zip

Check out lines 16456, 23205 and 23292. Seems to be an issue with the walker description maybe?

**Comment by elmokki** [comment]
Yeah. I've been ignoring description weirdness for ages now since the whole system needs a rewrite pretty much.

**Comment by elmokki** [comment]
Those are all commanders so it's because commanders have an extra special description generation.

**Comment by elmokki** [comment]
I think this got fixed with 0.6.23.
