### ISSUE TITLE
Foulspawn PD change a la 4.31

### ISSUE THREAD

**Issue by Ealb** [elmokki/nationgen#838]
> Create temporary units in their correct shape

Well. This should be messy and fun.

**Comment by elmokki** [comment]
Also amazing. This should be very easy to code as it should probably be just all about removing the current "dump montag results into pool instead of the recruitable units" code. It might need adding ability to duplicate montag units so that it can pick two copies of some crappy montag infantry though. I'm not sure if that already exists as a total failsafe, but here it might be fine with montag poses just not being removed from the pool at all.

However, I've been utterly swamped by work lately and seeing how my coding motivation is low during normal fairly lazy work amount, it's unlikely I can be arsed to implement this too soon.

**Comment by Ealb** [comment]
Grrrrrrr. I just tried After the Cataclysm, and I fear this was a false alarm, as the PD there remains in its default state.

If it in fact is meant to be the change I thought it was, I can probably fix it. Probably. My motivation's pretty awful ATM too.

**Comment by Ealb** [comment]
> 2017-06-11 12:18:57 +0200
> Modding: PD can use montags

Okay, this sounds like there's no way that I'm merely misinterpreting this to mean what I want it to mean this time, so... yay?

**Comment by elmokki** [comment]
This should definitely be it.

**Comment by Ealb** [comment]
*sob* Another false alarm, based on how After the Cataclysm is behaving.

As an aside, it occurs to me that it might be reasonable - okay, not reasonable, but *amusing* - to add montag'd heroes to AtC, so every nation has a chance to get any hero. And/or add prophetshapes to all the Grand Mage (and.or priest) shapes, assuming that adding that could be easily scripted.

I still want to see PD turn into a random jumbled mess, though...

**Comment by elmokki** [comment]
I closed this but I figured out a possible way it might work:

After the Cataclysm sets unit with #firstshape -<montag> as PD, but perhaps it works if you set the montags as the PD directly.

**Comment by Ealb** [comment]
Hmm. Worth testing, yeah.

**Comment by elmokki** [comment]
It works.

**Comment by Ealb** [comment]
What's the syntax?

**Comment by elmokki** [comment]
Pick #firstshape -1234 from a the template unit definition
Put #defunit1b -1234 (or whatever command for whatever pd spot) to nation definition

**Comment by Ealb** [comment]
...so... beautiful... *wipes tear*

**Comment by elmokki** [comment]
Montagged heroes are a neat idea once hero generation is rewritten to be more interesting. Prophetshapes I'm a bit less inclined to add. It's id use for an extremely minor thing.

**Comment by Ealb** [comment]
Oh, those weren't NG suggestions. Those were random After the Cataclysm suggestions if you ever mess with that again.

**Comment by Ealb** [comment]
Anyway, I'll see if I can't wrap up content enough for there to be a clean break point for a patch this week...

**Comment by elmokki** [comment]
This is now done!

**Comment by Ealb** [comment]
Would it be difficult to add a PDSelector chanceinc moduleid? I'd be inclined to weigh montag templates a lot higher than individual poses for Foulspawns and illithid hybrids, and I'd be tempted to weigh militia-filtered units a little higher.

**Comment by elmokki** [comment]
Currently there is no chanceinc related stuff in PD selection at all, so it'd take some effort to think the logic again. It just chooses the "best" units for PD based on some algorithm I wrote ages ago.

It's a thing that should happen at some point, but probably in a way that also thinks about generating new units for PD only use as was requested in one of the other issues.

**Comment by elmokki** [comment]
Also the individual montag outcomes cannot currently be generated as PD. Only stuff you can recruit basically.
