### ISSUE TITLE
0.6.22 release candidate

### ISSUE THREAD

**Issue by Ealb** [elmokki/nationgen#856]
Right, it's been six months since 0.6.21 and I'm not going to get any closer to finishing my not-quite-done crap before traveling, so I wrapped up things as best I could so if you want to do a release it should hold together. Content-wise, no new races, but a pile of little things. I'm really close to being done with 1-4 races, but I'm out of time, so... yeah. There's still more than enough just on the code side right now for a release in any case.

Or I can do one after the 5th. Either way.

Note that I've tested very little, so a stress test or three would be a good idea, but things pass SpriteGen at least, so the worst typos are fixed. Changelog is up-to-date, though possibly too short on detail. Flags haven't been tested at all, at least not by me; AlStar tested their bits and I cut-n-pasted them in, so they're probably all right, but it really needs verified, not least because I added my own new stuff too.

**Comment by Ealb** [comment]
(And as previously discusseded, I'll be incommunicado for a while, starting now.)

**Comment by elmokki** [comment]
There have been some months since the last update. There can be more time until the next one.

There's a slim chance I can be bothered to finish shore recruits for the next update and an even slimmer but existing chance that I'd do the whole UW nation shenanigans while I am at it.

**Comment by Ealb** [comment]
Right, back. Missing Sweden already (Fotografiska was lovely, BTW, although the temporary featured exhibit of horsey photography was moreso mildly interesting than enthralling, so my visit's timing could have been better). I may get some work done on this soonish, but if I'm "good" I probably will devote most of my spare time in the immediate future to cultivating/post-editing a subset of the 1100-ish pictures I took. Picking at NG may make a good visual distraction from that if it starts to feel like a chore, though.

**Comment by Ealb** [comment]
Nagas are done. In principle, I'd like to do elephant men as well, but it might be better to just get this out even if I'm totally convinced they're "almost done". For now, I'll aim for an "end-of-weekend" release, and see if I'm up to polishing those off.
