### ISSUE TITLE
No Lamias in Primary Race selection?

### ISSUE THREAD

**Issue by danayel** [elmokki/nationgen#865]
I can't select Lamias for a Primary Race. 

Are they a sub-race or intentionally unselectable?

**Comment by danayel** [comment]
👋  and thanks for a great tool btw. 😬  🙇

**Comment by elmokki** [comment]
It is news to me that we have Lamias in the mod at all, but that might just be me. The filtering options list everything the program uses and they don't have a race definition, so I guess they're a sub-race. Ealb knows more I suppose.

**Comment by danayel** [comment]
They are in there, 20% regen people. Says "lamia themes". I don't have one handy to show you though. I will bring it when I do. I guess we can close this for now :v:

**Comment by Ealb** [comment]
"Lesser lamia" are a demographic theme for Amazon nations. They were added with a below-average amount of fanfare back in 0.6.21.

**Comment by danayel** [comment]
Thanks @Ealb 🙇
