### ISSUE TITLE
Generator Sometimes Ignores Magic Diversity Restrictions

### ISSUE THREAD

**Issue by ForrestCinelli** [elmokki/nationgen#869]
I've noticed that the generator will sometimes pass nations that don't meet a given magic diversity restriction, even though it does sometimes reject nations based on these restrictions. 

Here is a particular example I found:
I used two magic diversity restrictions: at least 3 paths >= 4, and at least 6 paths >= 2 (in two separate magic diversity restrictions) to generate a single nation. The generator started on seed -1612231619 and accepted that nation. The nation only has 5 paths >= 2, including holy, including all randoms, and including nation-specific summonable mages (there were none). Attached is the .dm file and folder nation gen gave for that nation. 
[nationgen_kurpanzn.zip](https://github.com/elmokki/nationgen/files/1160806/nationgen_kurpanzn.zip)

Let me know if you need any other info!

**Comment by elmokki** [comment]
It would seem that magic diversity restrictions are being completely ignored since 0.6.22.

**Comment by elmokki** [comment]
Fixed in #870
