### ISSUE TITLE
Hoburg regional themes

### ISSUE THREAD

**Issue by Ealb** [elmokki/nationgen#88]
- All hoburg regional themes (except boreal) need some distinct content

**Comment by Ealb** [comment]
I think I may try to generalize some secondary-race associations into groups via "#chanceinc theme [not] `<theme>` `<mod>`"; i.e., oriental hoburgs are more like to get "oriental" (oriental humans, bakemono, etc.); Machakans are more likely to get "austral" (lizards), Van are more likely to get "boreal" (vaettir), Amazons are more likely to get "central" (minotaurs) or "tribal" (vaettir, barbarians), Argarthans are more likely to get "subterranean" (zotz, Abysian, Muuch), etc. I'd probably do the reverse as well by "#chanceinc anytheme [not] `<theme>` `<mod>`" to e.g. make oriental hoburg themes more likely on secondary-race-hoburgs for primary-race "#theme oriental" humans than boreal or other hoburgs,

**Comment by elmokki** [comment]
Is this and the other 0.6.0 issue still open? I think both are in. I'm mostly asking whether we should release or if there's still something to do.

**Comment by Ealb** [comment]
The other one just got closed by my reasonably-large update of junk I've been working/sitting on for 4-5 days. This one is iffy. I'd be happier in many ways if I put another night into working on differentiating these, but technically my "good enough" standard from the 0.6.0 issue has been met with basic bronze clockworks. I'll go ahead and close this, while opening an ongoing "polish hoburg regional themes" issue to replace it, since they're not done-done. We can release now if you think we're ready; regardless I'll keep plugging away on polishing these. The central and occidental hoburg improvements also lend themselves to doing overlapping work on making Hellenic/Mesoamerican human variants, so it's not as if ongoing work along these lines is deranged hoburg navelgazing. Well, I mean, not *entirely*...

**Comment by elmokki** [comment]
Yeah, there's no hurry. I was just wondering since judging by commits I thought the content was in already.

I might tinker with sacred generation a bit myself. I think the elves need to, in general, get less magic stuff than humans since they already have glamour, stealth and great stats. Currently they just get a price and cap only chance increases.
