### ISSUE TITLE
Dominions 5

### ISSUE THREAD

**Issue by elmokki** [elmokki/nationgen#892]
...has been announced: http://www.illwinter.com/dom5/

As little motivation as I've had to work with the program lately, it seems like the upgrade to Dominions 5 should be fairly simple. There are probably small things that we don't know yet, but the only mentioned things I noticed that affect nationgen are forts and recruitment points.

**Comment by Ealb** [comment]
Well, and content. I distinctly saw pictures of Abysians that looked like they were crossbred with salamanders. To say nothing of Uruk's Sirrush chariot.

There was also mention of "certain nations getting strong blesses" - I'd assume that'll be configurable, albeit most likely another national filter.

Plus ofc a bunch of new commands and special abilities.

It's for November, right? I may try to set myself to finish all the content I have started by then so I can do a big push to update existing stuff to include new content. For better or worse, I'll probably have roughly the same free time and motivation then as now. Ofc, the eternal problem with this is not getting distracted and making random other stuff, like the Fossilized Giant hero poses for Abysians I've been messing with for the last week...

**Comment by alguLoD** [comment]
There's also movement points, but AFAIK Dom5 automatically converts the old format by multiplying the map-move by eight (and then subtracting from that based on equipment). Might be worth considering in a few fringe cases, but nothing to lose hair over.

Some units and mounts might want to have the "Swimming" special ability (currently - in Dom5 - given to C'tissians, though not the chariot-using ones, and it seems Pythium's Serpent Riders don't have it either), especially those that currently have the Sail ability to represent something similar.

Of course, swimming can only cross unfrozen rivers, not actual sea provinces.

**Comment by Ealb** [comment]
Aye, on the content side there will be a pile of stuff to add. Less on the code side, I think, though. I'm sure there's more than what I see ATM, however.

https://forum.quartertothree.com/t/dominions-5-warriors-of-the-faith/131532/26 had a bunch of stuff listed I'd not seen on Steam, IW, or DomXMods forum, some of which is rather intriguing.

**Comment by elmokki** [comment]
I am uncertain I will buy the game on release so in that sense it is good if code changes will be minor as I would not be able to test them.

**Comment by Ealb** [comment]
It sounds like there's been a serious effort to expand strategic width; it will of course remain to be seen if that just means more features for powergamers to ignore when they figure out an optimal subset of strategies...

**Comment by alguLoD** [comment]
The guy on the QT3 forum is probably hanging out on Discord and noting down what the beta testers active there are saying, FWIW.

**Comment by Ealb** [comment]
Hmm, it occurs to me that recruitment points offer a way to have non-gold-reliant non-standard nation types like "masterless golems building more masterless golems" or non-materialistic undead collectives. That is more than a little intriguing...

More generally, recruitment points are one thing that might need worked into the system, though in the short term it would probably suffice to add a #command in each data file to give every basesprite some fixed value.

**Comment by Ealb** [comment]
For reference: http://www.illwinter.com/dom5/modmanual.html

**Comment by elmokki** [comment]
It'd be easiest to have a list of things we need to change. Movement and recruitment points come to mind at least.

That said, I am not too motivated to start tinkering to fix things unless they are incredibly simple fixes like the Dom3 -> Dom4 fort change was for nation mods. I might be slightly motivated to do some more major coding, but the thing is, the code is such spaghetti that my motivation suffers unless I start doing major rewrites and if I do that chances are I'll never finish. 

There are two things in my mind that I'd like to do. First is to just scrap current file format and give ability to make more complex chanceincs so you can just write (unit is human AND has fire magic 3 or more) rather than making huge strings of stuff. Obviously I'd make a program that converts content between formats, but it'd still be a huge mess of going through stuff to make chanceincs more sensible with new system so it's worth it. I'm pretty sure I will never do this due to that.

The second is more feasible and simpler. I'd just like to make the program generate some internal variables for chanceincs and stuff to use. Like, if the nation has very strong death-nature magic focus, just make a variable that chanceincs can query rather than some obscure "there is mage with nature and death magic" thing.

Sprite dumps should be easy to generate because I bet the file format is the same, but until there's a Dom5 version I don't think this project at least needs them. 

I also need to buy the game, but I guess I'm gonna do it.

**Comment by Ealb** [comment]
I'll admit that if you did the former of the two, my lackluster motivation would evaporate and I'd switch to rabid, task-oriented mode as far as sweeping chanceinc changes go.

Sprite dumps sooner than later would be lovely, but also a terrible, terrible distraction as I'm easily led astray by fiddly little graphics.

The biggest things I see are recruitment points (which could get a very simple placeholder change, as they're pretty straightforward, or a more long-legged calculating change) and map move. About to dive into a game, so I may very quickly have strong opinions about other things that need changed though. I'll try to be good and not (immediately) add "Abysia totally needs infernal crossbreed recruits" to the absolutely-must-do list...

**Comment by elmokki** [comment]
If you're genuinely interested in going through them it's not a huge deal since all I'd have to do is update parsers and go through the chanceincs in ChanceincHandler. Oh, and figure out a new file format. 

While JSON would be standard and efficient, I am unsure whether I like it. Something loosely like the syntax for Europa Universalis 4, Crusader Kings 2 and others might work, https://eu4.paradoxwikis.com/Event_modding, part Mean time to happen would show how a chanceinc would look, but it'd also mean quite complex structures for checking for magic for example fire magic below 2 or water magic at least 3:

`
chanceinc ={
or = {
not ={
    personalmagic ={
       path = fire
       level = 2
   }
}
    personalmagic ={
       path = water
       level = 3
   }
}
modifier = +0.5
}
`
+ add proper identation

I do like this stuff since while it means long definitions, it is quite comprehensible (also AND does not need to be specified, it would be assumed if there's no OR). 

This could be condensed by allowing stuff like personalmagic water 3 instead of having to use brackets for multiple parameters, but there's also the super simple option of:

`#chanceinc NOT personalmagic fire 2 OR personalmagic water 3 +0.5` which would actually require very minor changes to files (mostly the NOT-keyword moved in front of chanceinc since it wouldn't be stupidly tied to certain chanceincs and changing any below/above  stuff)

It would also probably need support for brackets so (x or y) and z and x or (y and z) can be identified. 

I'd also make these work on multiple lines because why not. Maybe require #endchanceinc so that comments directly after chanceincs work.

**Comment by Ealb** [comment]
The current file system is a large reason why I'm so slow to finish things I start - it feels like a lot of work mentally figuring out how to juggle things to make everything come out *just so*. I could probably make things easier on me by using some intermediate design tool other than going straight from my brain to Notepad, but a more robust file format would be *wonderful*. And if it allowed more data to be centralized, so much the better (I say this even as I acknowledge that the last year or two I've been a huge source of redundant or nearly-redundant data definition).

**Comment by elmokki** [comment]
If you have any ideas for how to structure data, either syntax or just files, feel free to tell! 

In terms of file structure I acknowledge that the current structure is a bit stupid considering how the entities contained in the biggest files are practically structured so that race -> pose -> item and yet the files themselves are structured in folders by poses -> race -> file / races -> file / items -> race -> file. 

Now, going for data/human/poses/items like the program actually used to do ages ago is very possible. However, the reason I originally went for current file structure is that it currently assumes that multiple races may share poses and multiple poses may share items, even across races. For items this is actually quite sensible: At least when I last tinkered with items, the so-called human weapons were used by many different races. For poses it is not very sensible because few if any poses are used by multiple races and for the most part I see little reason to do that ever.

Thus I think that it'd make sense to move pose files under races and instead of having to define "this file contains poses x" and "this race uses pose sets x" you could just define a filename in race definitions just like for items. As for items, well, they already refer to filenames so all you really need to do is move files and change definitions. I suppose it'd make sense to rename /items/ to /generic_items/ and move all pose/race-specific items somewhere into race folders. No point in doing that before poses are moved too though.

The thing is, these kinds of changes involve a lot of tedious work, though I suppose it'd be easy enough to code a program that goes through every single .txt file in /data/ and replaces #pose derp with #pose /data/race/poses/derp.txt for instance. If you feel like this sort of restructuring is worth it I might do it, but otherwise I can't be arsed.

Do you prefer either one of the two above  over the other for syntax?

**Comment by alguLoD** [comment]
Re; sprite dumps, the format is the same as in Dominions 4 (and indeed I won't deny that I've already looked at the sprites), so when you get around to that you don't need to worry.

**Comment by Ealb** [comment]
OMG, as far as "absolutely must-do" goes, hoburgbred *need* to ride the winged-salamander Hell Spawn like other hoburgs ride ozelotl.

(I'll look at the above file format stuff tonight when I can actually give it some proper consideration.)

**Comment by elmokki** [comment]
One more thing: We'll need to update databases, which I have previously done using Dom4Inspector. There may be some issues if Dom5inspector doesn't appear. Then again making Dom5inspector with Dom4inspector sources should be trivial if I can find out how to do the data dumps. Sadly Desura is dead so that info might not be publicly available anymore at least.

**Comment by alguLoD** [comment]
Desura's latest owners have managed to resuscitate it. They'd need a great deal of luck to get even a fraction of the old userbase back, but it should be possible to go through the forums and grab whatever you need now. [http://www.desura.com/games/dominions-4-thrones-of-ascensions/forum](url)

**Comment by elmokki** [comment]
Turns out that that doesn't matter since apparently the code to dump data from Dom5 is on Github too. If I had already bought the game, I bet it'd be easy to just run the same code on Dom5 and plug it into the inspector. Autocalc and such, if anything changed regarding it, would be broken but such is life (and it's not important for nationgen anyway since nationgen only uses a fraction of the data)

**Comment by Ealb** [comment]
Som5ModInspector is up (if somewhat buggy), so I don't have any more excuse to procrastinate and not dive into this.

> If you have any ideas for how to structure data, either syntax or just files, feel free to tell! 
> [...]
> Thus I think that it'd make sense to move pose files under races and instead of having to define "this file contains poses x" and "this race uses pose sets x" you could just define a filename in race definitions just like for items. As for items, well, they already refer to filenames so all you really need to do is move files and change definitions. I suppose it'd make sense to rename /items/ to /generic_items/ and move all pose/race-specific items somewhere into race folders. No point in doing that before poses are moved too though.
> .[..]
> Do you prefer either one of the two above  over the other for syntax?

This is definitely cleaner than what is going on now, and as much as a PITA as it'll be to update to this structure, this is the better of the choices.

Right now poses are also set for a given nation in themes, but as long as the poses files could be selected either place it would be fine like this, and could get rid of poses.txt et al. It's slightly convenient to use pose set names instead of pose file locations (especially in themes; that's the main place where there's multiple specifications of particular poses right now - possibly the ONLY place, actually), but it would be more clear even if it was slightly less tidy looking.

**Comment by elmokki** [comment]
Technically poses.txt can be left in and whenever file "humanposes" isn't found it can look from poses.txt. That way there's no need to change anything there either.

**Comment by Ealb** [comment]
Oh, and I really hate to say this since there was just a flag overhaul, but there should probably be another one since the flags are higher res. I'm gonna rank that as low-priority as far as updating stuff goes, though.

**Comment by Ealb** [comment]
In re: trying to centralize equipment lists, the major sticking point is sprites. It occurred to me that there are basically two straightforward ways to deal with that: exhaustive conditional lists, or decoupling image from other data.

Exhaustive lists would be straightforward; every time a new nation type with different graphics is added, the centralized weapon/armor/etc. file gets a new entry and it's gated with the appropriate chanceincs - although it could be tricky to get offsets right for all different items a nation uses from a single file in that case.

Decoupling would probably be easiest by having an optional command for item definitions, #altsprite or something, which would be a name rather than a URI, and a pose file would either have one or more altsprite files to define a list of altsprites, which would be something fairly simple like #new altsprite/#sprite foo.png/#recolormask foo.png/#offsetx foo/#offsety foo/#end; if an item file entry had an altsprite defined, and the nation also had one of the same name, that would be used instead of the item file sprite.

The former would be truly centralized, but could lead to seriously bloated item files. The latter would allow for a more streamlined, readable centralized item file but would require new data structures and would be less transparent.

**Comment by elmokki** [comment]
Is there enough uniformity to truly warrant such centralization? I mean, a broad sword could be weighed differently for different races or poses

**Comment by elmokki** [comment]
Though the latter approach should be trivial to code and won't probably break things too badly

**Comment by Ealb** [comment]
That's what I was wondering too. I was mostly thinking about this because you'd mentioned wanting more centralized equipment lists, or at least I thought you had. The main appeal I can see is that if it were done, making poses might be a lot easier. It might require multiple themed central lists though: primitive iron, normal iron, advanced iron, occidental, etc. Having said all that, though I'm not terribly concerned about this if you're not.

The latter could be hand for mages, probably. That's a place where it seems like the chanceincs are more likely to be the same across races since the mage themself is more likely to be why it got picked but the images might vary a lot. Even here, I'm still not terribly worried about it, though.

**Comment by elmokki** [comment]
I think just moving files around will probably make things clean enough. If item definitions were much more complex it would be a good idea to unify things, but currently they are really Sprite definitions with IDs and #armor

**Comment by elmokki** [comment]
Also, on an unrelated note, I think rec points will be 1000*(race gcost + pose gcost + basesprite gcost + adjustment) unless unit has it specified. Less readable in summaries but eh, vanilla stuff relies extensively on such autocalc. That formula probably approximates the "base" gcost pretty well. Not sure how extensive adjustments troop filters or sacreds need, but at least stuff like the militia filter does need  it.

**Comment by elmokki** [comment]
In case you did not notice, armor map move penalty (for body armor only) is in databases now. I am unsure whether this will have any meaning, but oh well.

**Comment by Ealb** [comment]
Hmm, probably need to check if this is universally applied or if some units are getting extra MM offset so their net movement is higher than other comparable less-armored troops. Without looking, it *seems* like it's pretty uniform, though.

**Comment by elmokki** [comment]
I am just unsure whether this matters to use at all. I can't think of anything since, as far as I understand, map move is now automatically calculated from the base amount anyway in game now.

**Comment by Ealb** [comment]
Well, previously we had some nations less affected by armor than others with the armor encumbrance modifiers. Vanilla is definitely doing this to a certain degree based on a quick look at LA Pyth (the field armies have base MM of 20 vs. garrison-type troops with MM of 14, leading to 18/16 final MM vs. 12/10 for the respective line/elite LA Pyth legionaires.

I'll look over some other nations later when I have more time. My instinct is that there may be some troops getting more MM than comparable chassis would suggest, but it's more a matter of them flat-out being faster than getting MM specifically to offset armor penalties.

**Comment by Ealb** [comment]
I want to say that we can close this, as I think we've added support for everything discussed as specifically needed material, although there was some interesting rambling about restructuring. Still, in the interest of actually closing resolved issues, I'm gonna close this.
