### ISSUE TITLE
Size-3 hoburg power armor

### ISSUE THREAD

**Issue by Ealb** [elmokki/nationgen#90]
- Add weapons and some modest special abilities for size-3 armor

**Comment by elmokki** [comment]
I'm not sure how feasible it is (and it's 100% up to you what you want to draw) but it would be cool and/or funny if the super mecha hoburgs had a special feature slot that would always give them something: One might have wings and the other might have a shoulder-mounted flame gun of some sort. Alternatively, of course, you could have a few of these slots without 100% chance to generate so you could get a vanilla unit or an unit with wings and a shoulder mounted lightning rod.

It could even be done with #renderslot so you could feasibly have the actual sprite drawn in correct place. 

Hell, I might even be tempted to try to draw this kind of crap myself.

**Comment by Ealb** [comment]
The way I did it with the size-2 armor is there's a 20% chance for non-elite units to generate a "specialslot" and a 100% chance for elites/sacred to generate one, and the specialslot would use #needs to assign a special weapons like the shocklance, or just straight-up give them better gears (no exhasution) or a sealed helm for #pooramphibian or wings, etc. It was a bit more complicated for them because each option might change the number of item slots, but unless the bigger ones get something replacing one of their hands (and they're big enough that that doesn't seem necessary) they should all be able to get away with the same set of 2 hands + 3 misc (3 because they're essentially in a vehicle, unlike the smaller armor). Furthermore, since I was doing the size-3 as elite/sacred only, I'd probably go with 100% chance to get a modification.

Which is to say, this was definitely on the drawing board. I don't think #renderslot would be necessary unless it's replacing a hand or something, because the size-3 suits are even less variable than the size-2 ones - they're pretty much going to be a dummy basesprite, armor, mainhand and/or offhand, hands, and that's it for non-special slots. That's another reason I want to do special features - it'll make them more distinctive.

If you have any inspirations, feel free to craft them; otherwise I'll plod along and get them some later this week.
