### ISSUE TITLE
Formation fighter

### ISSUE THREAD

**Issue by Ealb** [elmokki/nationgen#900]
I haven't had an extended period where I had both time and motivation to work on things, but I've thought about things some. One point that is clear at this point is that formation fighter needs to be worked into a range of size-dependent filters/templates instead of just one universal filter. The main question is how many.

* For the most simple interpretation, there would be four: size 1, 2, 3, 4+ giving FF(1), (2), (3), (6) respectively. This would allow an extra unit of the same size in the square, although I'd be tempted to experiment with (6) to see how that interacts with sizes less than 6; it might be the case that there should be 6 filters.
* If the extra space doesn't need to be filled with more formation fighters, it might be better to do (1), (2), (3), (4), (3), (2) so really big formation fighters get extra room for chaff rather than 2 size-6 units per square.
* Should more than one extra troop be possible? I.e., should there be levels of FF filters? Size 1 could quite reasonably have FF (2), fairly reasonably have FF (3), and for small or extremely drilled size 1 I could see even see FF (4). This assumes it's even possible to exceed 6 in a square, though, which I haven't checked. Pity if it's not, but regardless, there's the question of whether size 2 should be able to do FF (4) to get 5 in a square, or size 3 getting 4 with FF (6),
* These aren't necessarily mutually exclusive, ofc.

**Comment by elmokki** [comment]
If I were to bother to redesign how filters work it'd be possible to just add conditional effects.

Just like probability could be affected "if unit size is 3 add x, if unit size is 2, add y" you could theoretically make the effect ""

This would, however, require quite some work on definitions or some clunky #conditionalcommand thing. As much as I like the current simple syntax, going for something like what the Paradox games use does definitely have upsides.

**Comment by Ealb** [comment]
Okay, I think I have the gist of the mechanics; they're both simpler and more complicated than I'd originally thought. Mostly simple, though. So pretty much any unit with FF > 1 can be part of a FF square, and the number of troops that can fit into a square (however many FF units fit into 6 spaces) + (size of FF units trying to fit / lowest FF value of any unit trying to fit, rounded to the nearest whole number). E.g., if you have Jotun Spearmen with FF 1, they're 1 to a square; if they have FF 2 - FF 5, they're 2 to a square; if they're FF 6 - 9 they're 3 to a square; and if they're FF 18+, they're 6 to a square. If the FF 20 Spearmen are combined with FF 12 Niefel Giants (which are hilarious, BTW), a square could hold 3 Giants, 2 Giants and a Spearman, 1 Giant and 3 Spearmen, or  6 Spearmen.

Poor FF is mostly simpler; the base capacity of a square is reduced by the biggest negative FF for the purpose of negative FF grouping up, but otherwise there's no effect. So size 2/FF -2 means there can only be 2 of those in a square, or 1 plus 2 other non-negative FF units; size 2/FF -3 means they're 1 to a square with each other, but combine normally with normal troops. It appears that Poor FF trumps normal FF as well, so size 2/FF -1 plus size 4/FF 4 will be 2/square each, but never group up.

Tragically, the upper limit is 6, so FF is useless for hoburg hoplites.

--

If we only want one extra troop per square, the filter can simple be disabled for size 1 (it's not useless, since it would let them pack into other FF squares, but it's very low-value unless there's mixed-sized FF units), give FF 2 for size 2, and give FF 3 for everyone else. This would be the simplest route.

Poor FF would also make for a reasonable minor malus, akin to EA Abysian Burning Ones. In that case, it would probably only need to be -1... although I could maybe see -2 for size 1, albeit as a significant malus. Poor FF -1 could probably serve as an unpleasant national filter, actually. Poor Martial Traditions or somesuch.
