### ISSUE TITLE
Add bodytype commands to definitions

### ISSUE THREAD

**Issue by Ealb** [elmokki/nationgen#917]
This should be pretty straightforward, except maybe for foulspawn. Possibly even for them. But anyway, 5.15 changed hit location mechanics according to unit body types, and 5.16 made it so modded units could define their body types rather than all being formless blobs. The bodytypes also come with defined itemslots, which I assume are just defaults and can be overridden, but we shall have to see.

Ref: http://s7.zetaboards.com/Dom3mods/single/?p=10002164&t=1273998

**Comment by elmokki** [comment]
So, this is necessary instead of slots dictating it?

**Comment by Ealb** [comment]
Well, right now everything defaults to blobs and can only receive body hits (which makes helmets useless, among other things). So to have normal targeted hit locations, yeah, it's gonna be necessary. It'll be one-line commands per unit, though - and really, it'll be straightforward unless we're cobbling the shape together dynamically.

**Comment by elmokki** [comment]
Well, I mean, I suppose this makes the itemslot code currently in fairly useless and is nice as such, but I feel like it's not a very smart coding solution from Illwinter compared to just looking at slots. 

From what I understand we don't really need to care about this stuff a lot indeed. Just put #humanoid on everything and one of the beast things on some very rare things (are there headless enough foul spawn to warrant #troglodyte?). It does say that #mountedhumanoid and #humanoid have the same hit locations so just using #humanoid and removing feet does the same as far as I understand.

**Comment by elmokki** [comment]
Oh, the snek men probably need #naga too.

**Comment by Ealb** [comment]
I think the main reason we have this complicated mess is the half-under-the-hood height mechanics for hit locations - bitey things have their heads lower, so they're still hitable even when giants. By and large, though, yeah - itemslots point to most of this just as well.

**Comment by Ealb** [comment]
Hmm, and centaurs/mounted units can still get crippled/limp despite not having feet slots. It still feels like more complication than was needed - exceptions could have commands and the rest could use slots.

**Comment by elmokki** [comment]
So, how about assigning this automatically?

If unit has #lizard, #quadruped, #snake, #bird, #djinn or #miscshape, it is that.
If unit has standard slots, it's a humanoid.
If unit lacks feet, it is #mountedhumanoid or #naga depending on whether it has #mounted
If unit has feet but does not have head, it has #troglodyte

There's no good way to differentiate djinn and naga so #djinn has to be custom (#coldblooded is not good enough because you could have a naga-like non-naga). #bird could be differentiated from #miscshape by #flying. #snake cannot be identified from #miscshape and finally #quadruped and #lizard cannot be identified too well, though head slot could do it in theory.

**Comment by Ealb** [comment]
Right now, my plan was just to handle it in the data files, though you're probably right to suggest having a catch-all assigned in the source if there weren't any others present. NG almost exclusively deals with humanoid-ish things, so a lot of those aren't really needed outside of explicitly-defined fixed-stat monsters.

Djinn isn't really something we have any of, though I suppose if we added elemental "children" (slyphs, magma kids, earth gnomes, undines) as a nationtype it would be nice to support.

If you want to do this in the code, I'll refrain from doing a sweep to add bodytype definitions in the data files, though. There is some appeal to automating it...

**Comment by elmokki** [comment]
Just to make sure, the commands are just #humanoid #lizard etc and not #bodytype lizard etc?

**Comment by Ealb** [comment]
Yup, just tested. #<type>; #naga was enough to steal away a Caelian scout's feet.

Relatedly, it's irritating that there are additional bodytypes without new injuries. If we're making birds distinct, there should be wing hits that prevent flying for things that fly by physical means...

**Comment by elmokki** [comment]
Could you test whether #itemslots 15494 after #naga can give feet back?

**Comment by Ealb** [comment]
Yay, it does! :)

**Comment by Ealb** [comment]
...but before it gets overridden, as one would suspect. So itemslots after bodytypes.

**Comment by elmokki** [comment]
As suspected.

Okay, so:

1. Any body type or copystats -> skip
2. Unit has feet and at least one arm
2a: If head, then #humanoid 
2b: If no head, then #troglodyte 
3: Unit has an arm (but no feet)
3a: If unit has a mount slot item, #mountedhumanoid
3b: If unit does not, #naga  
4: Unit has feet, but no arm -> #quadruped
5: Unit has no feet nor arm -> #miscshape 

Now, two last cases should never happen, but I think it's better to have them there.

Also, shapechanges are not handled by this. Any non-#copystat shapechanges should thus get suitable shapes and possibly itemslots added to them.

**Comment by Ealb** [comment]
5.17 "fixes" #bird and #djinn, though I don't know how yet.

#footattoo as well - I suppose that means filters for tribals with the appropriate totem animal themes, and fixed chances to get a spell to awaken them - with variants needing made for non-Nature nations, or should the tattoos be Nature-nation only? We could just do a holy spell #copyspell so the tatttooed nations aren't reliant on having mage-priests (and it creates more utility for non-mage priests)...

Terrain lab/temple costs is nice, and on a modding-unrelated note, we finally get variable twiceborn and bronze-age indies (which means it may be time for me to try to get sprite dumping to work... I wonder if my problem with that is 32 bit scripts on 64 bit machines)!

**Comment by elmokki** [comment]
Since the tattoos are animal-based in in game tooltips etc, nature restriction is sensible I suppose. If they were more generic than they are, then not. I mean, it'd be neat to have a blood nation that has magic blood warpaint that used the same mechanics and in a more general sense, why couldn't magic tattoos be activated by whatever magic they are attuned to?

I run the python spritedump script on 64 bit Windows 10. If you wish, I can just update the dump fairly trivially.

**Comment by Ealb** [comment]
Yeah, if you could that would be nice. I've had huge problems trying to get it to run, and have never figured out why, multiple CS degrees not withstanding. Bird is apparently armless, djinn is naga without a lower head, so if you really wanted to automate it, it would be with no biting, but it's exotic enough that I'd be okay with using naga as default - or vice-versa.

Re: tattoos, the current spell is N1H1, which means we would either want to require tatted-up nations to get a 100% chance of low-level mage-priests, or we probably wanna make one or more copies. Blood and death both seem like good non-nature tattoos, but astral is a bit too refined. Hmm... could we add a command to force a specific tier of mage with a minimum set of paths, so tribals could force T1 N1H1/D1H11/B1H1 mage-priests to be created?

**Comment by elmokki** [comment]
I'll post a sprite dumb on dom4mods soonish.

The point about tattoos was that the tooltips for them in game are "magic boar/wolf/bear tattoo", which does heavily point towards nature magic. 

N1H1 forcing is something that should come, but it should probably be thought out as a part of a larger update that gives more flexibility than strictly that. I want to randomize path priorities as one of the first things in nation mod and I want to make commands that force certain magic paths to be prominent. 

Currently the priority just ranks paths and doesn't really guarantee that anything beyond the first path is going to be very prominent, ie fire, water, air, astral... priority can lead to 3F1?, 2F1?, 1F mages or something. It would be nice if you could tell the program to force fire and water to be prominent, in which case it would only consider mage setups that either have mages with multiple paths at highest level or mage setups that have multiple mages of at least one tier.

The way N1H1 forcing would happen is to force nature as a priority path, force priority paths for tier 1 mages and force mage-priesthood for at least tier 1. Alternatively, +N to priests is possible I suppose, but I think I don't want to ever make priest generation make tier 1 priests with magic. Those should be mages. H2 and H3 priests could have minor magic like MA Marignon though.

**Comment by elmokki** [comment]
I do suppose you could stretch the animal tattoos to death and blood though, yes.

**Comment by Ealb** [comment]
It's a shame we can't define our own tattoos. I want shark tattoos, dammit!

**Comment by elmokki** [comment]
I bet the Warhammer mod people would love to get savage orc warpaints modelled with the mechanic too.
