### ISSUE TITLE
Dom5: Commanders Without RP Cost.

### ISSUE THREAD

**Issue by Legendsmith** [elmokki/nationgen#933]
I've often had commanders generate without RP costs. Here's an example. I haven't confirmed but it seems to happen for some types of humans.
[steel and blood bugged.zip](https://github.com/elmokki/nationgen/files/1819568/steel.and.blood.bugged.zip)
![image](https://user-images.githubusercontent.com/1914417/37526567-d932ca2e-2983-11e8-809c-4a69fa0381c0.png)

**Comment by elmokki** [comment]
Current released version (0.7.0-RC1) is not really supposed to have such fancy features as consistent RP costs for leaders: It's all based on how well the game automatically assigns the costs. 0.7.0-RC2 should though, whenever we release it!

**Comment by Legendsmith** [comment]
The point here is that it seems to be generating it just fine for most things but not a few human types.

**Comment by elmokki** [comment]
Yeah, but I mean, that version isn't doing anything to set the costs in the first place so the only thing we can do is to set them, which is done in RC2.
