### ISSUE TITLE
Overly-aggressive pose selection?

### ISSUE THREAD

**Issue by Ealb** [elmokki/nationgen#94]
There's something odd going on with pose selection. Oriental-theme hoburgs have boreal poses chances reduced to 0.01 and oriental bumped up to 1, but there's usually as many if not more boreal poses as oriental. Increasing the oriental bump-up to 10 didn't seem to really change that. On a possibly-related note, tier restrictions on mages seem to be ignored right now. Integrated caveman ally mages are restricted to tier 1, but I'm seeing races with only caveman mages. E.g:
![preview_ababurg](https://cloud.githubusercontent.com/assets/12613576/8396519/71750a84-1d77-11e5-8242-183a7b37f09b.png)

**Comment by elmokki** [comment]
The caveman mage thing is due to the mage pose picker not realizing that not all races have higher tier mages.

For pose selection the reason seems to be that the selection for troops is currently being done primarily by armor instead of poses. I think I might rewrite this.

**Comment by Ealb** [comment]
It's probably actually worse than that for the cavemen, as this is from the theme that injects a caveman mage pose into hoburgs. So race(0) had "caveman shaman" who are #tier 1 and #notfortier 2/3, and hoburg mages who are #tier 1/2/3. The mage picker still chose the caveman poses over the hoburg poses.

**Comment by elmokki** [comment]
The possible poses to roll from are  done this way:

1. Get all poses with #tier x and not #primaryraceonly if secondary race
2. If no poses were found, get all poses without #notfortier x and not #primaryraceonly if secondary race
3. Error message

I fixed my hypothesis of the cause, but if that truly isn't it (like, with having cavemen as allies AND as secondary race) it will need some debugging with a seed - which might've broken with the change.

**Comment by Ealb** [comment]
No, this wouldn't have been it as the secondary race in that case should have been Humans (oriental). If you want to merge the changes I can grind out a new bad example; I wanna say this wasn't uncommon so it should recur.

**Comment by elmokki** [comment]
-> caveman shaman - [tier 1, notfortier 2, notfortier 3] did not have #notfortier 2

This debug message summarizes the issue I believe.

**Comment by elmokki** [comment]
Yeah. It's looking for #notier and not for #notfortier. I wonder how long this has been there.

**Comment by elmokki** [comment]
Also,
CRITICAL FAILURE, IMAGE FILE /graphics/highmen/weapons/hammer_iron.png CANNOT BE FOUND.
CRITICAL FAILURE, IMAGE FILE /graphics/highmen/weapons/hammer_iron.png CANNOT BE FOUND.
CRITICAL FAILURE, IMAGE FILE /graphics/highmen/weapons/hammer_iron.png CANNOT BE FOUND.
CRITICAL FAILURE, IMAGE FILE /graphics/highmen/weapons/hammer_iron.png CANNOT BE FOUND.

Some other weapons spammed similar stuff. I'm not 100% up to date with your branch so I'm not sure if you've fixed them already.

**Comment by Ealb** [comment]
Yeah, caught that already. All the iron weapons should be foo.png, not foo_iron.png.

**Comment by Ealb** [comment]
After changing notier->notfortier in the source, seeds get broken into pieces, but in a way that looks like the mage issue is satisfactorily

![preview_elenfurt](https://cloud.githubusercontent.com/assets/12613576/8396685/5c1bd31e-1d7e-11e5-9a4d-d5737371a22c.png)
 resolved.

**Comment by elmokki** [comment]
Don't commit that or it will conflict with my last few commits.

**Comment by Ealb** [comment]
Duly noted, I'll revert my local copy. Oh, and that last preview I generated has a caveman with a spear and an offhand club, so it looks like that might still be with us.

**Comment by elmokki** [comment]
That may be because you haven't tagged the pose or mainhand weapon (or race or a filter, but those aren't relevant here) with #troopweapon

**Comment by Ealb** [comment]
Hard to say for sure since adding that tag pretty thoroughly broke seeds, but there's certainly no sign of it after the change, so hopefully that did it.

**Comment by Ealb** [comment]
Hmm. Priest generation doesn't appear to be checking tier eligibility. Some of that is "notier" again (lines 1862 and 2182 of MageGen.java) but even after I fix those I still see a notfortier3 caveman ally pose getting H3. I'll update my fork to a debug case for this with those two lines being the only code changes, and all data files set to generate an ineligible H3 from EA seed -346769806.

**Comment by elmokki** [comment]
It was because new priest base were being generated at holy level + 1 for some reason. The only new priest base generated ever is the highest level priest (others are derived) so I would bet that this was originally done to make your only H1 priest a bit more "high priesty" since hey, it's your highest level priest. The rest were always being generated at correct level though.

The bug here was that if priest had H3, it tried to generate as tier 4. Unsurprisingly cavemen were able to be tier 4.

Now that I wrote this I think I'll add the +1 level thing back but I'll cap it to 3.
