### ISSUE TITLE
Climate preferences from themes don't appear to be applied

### ISSUE THREAD

**Issue by Ealb** [elmokki/nationgen#942]
Right now, it looks like any nation which has a theme entry of the form:

#racedefinition "#nationcommand '#idealcold -3'"

is not having any climate preference set; those who have this set directly in the race file still seem to be getting it. This kinda worries me because if this isn't being set, there may be other themes-modifying-race-definitions shenanigans that aren't being applied. I've had no time to test this beyond noting that it's happening, and I'll not have a chance to look at this before tomorrow, so I don't know if it's more severe or something dumb and simple.

**Comment by elmokki** [comment]
This sounds weird because I don't think anything regarding it has changed, but it should be relatively easy to check it out.

**Comment by elmokki** [comment]
Okay, idealcold +3 nation themes end up printing "#idealcold +3" which is fubar at least.

**Comment by elmokki** [comment]
Okay, this was dumb: Nations have for some time been handling nation commands of primary race before adding themes.
