### ISSUE TITLE
Sacreds that cost less than base racial values

### ISSUE THREAD

**Issue by Ealb** [elmokki/nationgen#974]
Is there an obvious reason why sacreds might cost less than the base racial cost? Right now, I've seen a lot of 65g elephants, whereas the basesprite imposes gcost 70 as a base. These are sacreds with other powers, too.

E.g.
-- Generated with version 0.7.0-RC5.
-- Generation setting code: 5
-- Nation 120: Guwaoor generated with seed -705313193

** Ancient Sentinel (Dantih), 65g, 35r, Exceptional Long Spear, Scale Mail Hauberk, Iron Cap, Buckler.
--- Capital only, Sacred, growthpower and Infantry sacred

**Comment by elmokki** [comment]
I am really not feeling like debugging this right now, but there should be some old cost reduction code in sacredgen that might be the culprit.

**Comment by elmokki** [comment]
I mean, after all, chances are I wrote everything with humans in mind.

**Comment by Ealb** [comment]
Aye, no worries, I'll have a look. I just wanted to ask before code-diving in case there was some extremely glaringly explanation.

**Comment by Ealb** [comment]
...there is indeed a magic number of 70 in adjustGoldCost, so all sacred elephants were getting the "excessively priced sacred" discount. I replaced the 70 threshold with a dynamic one of 25*size so big lumbering brutes operate on their own scale.
